recipe: default.v1

assistant_id: 20240905-083714-quantum-spread

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 50
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.2


policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_threshold: 0.3
    nlu_threshold: 0.2
    fallback_action_name: "utter_default"
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 50
  - name: TEDPolicy
    max_history: 5
    epochs: 50
    constrain_similarities: true
