-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 04, 2025 at 11:06 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cstu`
--

-- --------------------------------------------------------

--
-- Table structure for table `cgroup`
--

CREATE TABLE `cgroup` (
  `groupCode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `groupCourse` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `groupType1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `groupType2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `groupType3` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `requireUnit` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `cgroup`
--

INSERT INTO `cgroup` (`groupCode`, `groupCourse`, `groupType1`, `groupType2`, `groupType3`, `requireUnit`) VALUES
('61-100', 'y61', 'วิชาศึกษาทั่วไป (30)', '', '', 30),
('61-101', 'y61', 'วิชาศึกษาทั่วไป (30)', '', 'ส่วนที่ 1 : หมวดสังคมศาสตร์', 6),
('61-102', 'y61', 'วิชาศึกษาทั่วไป (30)', '', 'ส่วนที่ 1 : หมวดมนุษยศาสตร์', 3),
('61-103', 'y61', 'วิชาศึกษาทั่วไป (30)', '', 'ส่วนที่ 1 : หมวดวิทยาศาสตร์กับคณิตศาสตร์', 3),
('61-104', 'y61', 'วิชาศึกษาทั่วไป (30)', '', 'ส่วนที่ 1 : หมวดภาษา', 9),
('61-105', 'y61', 'วิชาศึกษาทั่วไป (30)', '', 'ส่วนที่ 2 : วิชาบังคับ', 6),
('61-106', 'y61', 'วิชาศึกษาทั่วไป (30)', '', 'ส่วนที่ 2 : วิชาเลือก', 3),
('61-200', 'y61', 'วิชาเฉพาะ (93)', '', '', 93),
('61-201', 'y61', 'วิชาเฉพาะ (93)', 'วิชาแกน (12)', 'วิชาบังคับ 4 วิชา', 12),
('61-202', 'y61', 'วิชาเฉพาะ (93)', 'วิชาเฉพาะด้าน (36)', 'กลุ่มประเด็นด้านองค์การและระบบสารสนเทศ', 3),
('61-203', 'y61', 'วิชาเฉพาะ (93)', 'วิชาเฉพาะด้าน (36)', 'กลุ่มเทคโนโลยีเพื่องานประยุกต์', 6),
('61-204', 'y61', 'วิชาเฉพาะ (93)', 'วิชาเฉพาะด้าน (36)', 'กลุ่มเทคโนโลยีและวิธีการทางซอฟต์แวร์ (เลือกแผน)', 12),
('61-205', 'y61', 'วิชาเฉพาะ (93)', 'วิชาเฉพาะด้าน (36)', 'กลุ่มโครงสร้างพื้นฐานของระบบ', 12),
('61-206', 'y61-100', 'วิชาเฉพาะ (93)', 'วิชาเฉพาะด้าน (36)', 'กลุ่มฮาร์ดแวร์และสถาปัตยกรรมคอมพิวเตอร์\r\n(สำหรับนักศึกษาวิชาเอกวิทยาการคอมพิวเตอร์และสารสนเทศ)', 3),
('61-207', 'y61-011', 'วิชาเฉพาะ (93)', 'วิชาเฉพาะด้าน (36)', 'กลุ่มฮาร์ดแวร์และสถาปัตยกรรมคอมพิวเตอร์\r\n(สำหรับนักศึกษาวิชาเอกคอมพิวเตอร์ประยุกต์และวิชาเอกเทคโนโลยีการเรียนรู้)', 3),
('61-208', 'y61-100', 'วิชาเฉพาะ (93)', 'วิชาเอก (39)', 'วิชาเอกบังคับ คอมพิวเตอร์และวิทยาการสารสนเทศ', 27),
('61-209', 'y61-100', 'วิชาเฉพาะ (93)', 'วิชาเอก (39)', 'วิชาเอกเลือก คอมพิวเตอร์และวิทยาการสารสนเทศ', 12),
('61-210', 'y61-010', 'วิชาเฉพาะ (93)', 'วิชาเอก (39)', 'วิชาเอก คอมพิวเตอร์ประยุกต์', 39),
('61-211', 'y61-001', 'วิชาเฉพาะ (93)', 'วิชาเอก (39)', 'วิชาเอก เทคโนโลยีการเรียนรู้', 39),
('61-212', 'y61', 'วิชาเฉพาะ (93)', 'วิชาบังคับนอกสาขา (6)', '', 6),
('61-300', 'y61', 'วิชาเลือกเสรี (6)', '', '', 6),
('66-100', 'y66', 'วิชาศึกษาทั่วไป (30)', '', '', 30),
('66-101', 'y66', 'วิชาศึกษาทั่วไป (30)', '', 'หมวดความเท่าทันโลกและสังคม', 6),
('66-102', 'y66', 'วิชาศึกษาทั่วไป (30)', '', 'หมวดสุนทรียะและทักษะการสื่อสาร', 9),
('66-103', 'y66', 'วิชาศึกษาทั่วไป (30)', '', 'หมวดคณิตศาสตร์ วิทยาศาสตร์ และเทคโนโลยี (เลือก)', 3),
('66-104', 'y66', 'วิชาศึกษาทั่วไป (30)', '', 'หมวดสุขภาวะและทักษะแห่งอนาคต วิชาบังคับ', 6),
('66-105', 'y66', 'วิชาศึกษาทั่วไป (30)', '', 'หมวดสุขภาวะและทักษะแห่งอนาคต วิชาเลือก', 3),
('66-106', 'y66', 'วิชาศึกษาทั่วไป (30)', '', 'หมวดการบริการสังคมและการเรียนรู้จากการปฏิบัติ', 3),
('66-200', 'y66', 'วิชาเฉพาะ (87)', '', '', 87),
('66-201', 'y66', 'วิชาเฉพาะ (87)', 'วิชาแกน (12)', 'วิชาบังคับ 4 วิชา', 12),
('66-202', 'y66', 'วิชาเฉพาะ (87)', 'วิชาเฉพาะด้าน (42)', 'กลุ่มประเด็นด้านองค์การระบบสารสนเทศ', 3),
('66-203', 'y66', 'วิชาเฉพาะ (87)', 'วิชาเฉพาะด้าน (42)', 'กลุ่มเทคโนโลยีเพื่องานประยุกต์', 9),
('66-204', 'y66', 'วิชาเฉพาะ (87)', 'วิชาเฉพาะด้าน (42)', 'กลุ่มเทคโนโลยีและวิธีการทางซอฟต์แวร์', 12),
('66-205', 'y66', 'วิชาเฉพาะ (87)', 'วิชาเฉพาะด้าน (42)', 'กลุ่มโครงสร้างพื้นฐานของระบบ', 15),
('66-206', 'y66-10', 'วิชาเฉพาะ (87)', 'วิชาเฉพาะด้าน (42)', 'กลุ่มฮาร์ดแวร์และสถาปัตยกรรมคอมพิวเตอร์\r\n(สำหรับนักศึกษาวิชาเอกวิทยาการคอมพิวเตอร์และสารสนเทศ)', 3),
('66-207', 'y66-01', 'วิชาเฉพาะ (87)', 'วิชาเฉพาะด้าน (42)', 'กลุ่มฮาร์ดแวร์และสถาปัตยกรรมคอมพิวเตอร์\r\n(สำหรับนักศึกษาวิชาเอกคอมพิวเตอร์ประยุกต์)', 3),
('66-208', 'y66-10', 'วิชาเฉพาะ (87)', 'วิชาเอก (30)', 'วิชาเอก คอมพิวเตอร์และวิทยาการสารสนเทศ', 30),
('66-209', 'y66-01', 'วิชาเฉพาะ (87)', 'วิชาเอก (30)', 'วิชาเอก คอมพิวเตอร์ประยุกต์', 30),
('66-210', 'y66', 'วิชาเฉพาะ (87)', 'วิชาบังคับนอกสาขา (3)', '', 3),
('66-300', 'y66', 'วิชาเลือกเสรี (6)', '', '', 6);

-- --------------------------------------------------------

--
-- Table structure for table `courses-61`
--

CREATE TABLE `courses-61` (
  `courseGrorp` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `courseID_EN` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `courseID_TH` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `courseName_EN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `courseName_TH` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `courseUnit` int(10) NOT NULL,
  `courseHour` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `notCount` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `mustTaken` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `mustTaken_EN` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `courseDescrip_EN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `courseDescrip_TH` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `courses-61`
--

INSERT INTO `courses-61` (`courseGrorp`, `courseID_EN`, `courseID_TH`, `courseName_EN`, `courseName_TH`, `courseUnit`, `courseHour`, `notCount`, `mustTaken`, `mustTaken_EN`, `courseDescrip_EN`, `courseDescrip_TH`) VALUES
('', 'BA291', 'พบ.291', 'Introduction to Business', 'ธุรกิจเบื้องต้น', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'The course aims to provide a comprehensive introduction to the key operations of business, namely finance, accounting, marketing, human resource and production management, and management information system, placed within organizational, forms of businesses, environmental, legal and managerial context. Underlying business concepts will be discovered through the study of real-world examples and fundamental business plans.', 'ลักษณะของธุรกิจสภาพแวดล้อมและรูปแบบความเป็นเจ้าของธุรกิจ การบริหารธุรกิจกิจกรรม\r\nทางธุรกิจด้านการผลิตการตลาดการเงินการบัญชีการบริหารสารสนเทศ และการบริหารทรัพยากรมนุษย์\r\nทั้งนี้เพื่อปูพื้นฐานแนวความคิดของการบริหารธุรกิจ และให้เกิดความคิดรวบยอดผ่านการจัดท าแผนธุรกิจ\r\nหมายเหตุ เป็นวิชาส าหรับนักศึกษานอกคณะพาณิชย์ฯที่ประสงค์จะเรียนรายวิชาต่าง ๆ ของคณะฯเป็นวิชาโทควรจะเรียนวิชา พบ.291 ก่อนวิชาอื่นเพื่อใช้เป็นพื้นฐานในการเรียนวิชาต่างๆของคณะพาณิชย์ฯ'),
('', 'CS101', 'คพ.101', 'Discrete Structures', 'โครงสร้างแบบไม่ต่อเนื่อง', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Intensive introduction to discrete mathematics as applied in computer science: Basic logic and its main application in Digital logic, proof techniques, sets, functions, relations, Boolean algebra, basic of counting, and graphs.', 'ตรรกศาสตร์เบื้องต้นและการประยุกต์ใช้ในวงจรดิจิทัลพื้นฐาน วิธีการพิสูจน์ เซต ฟังก์ชันความสัมพันธ์ พีชคณิตบูลีน พื้นฐานการนับ และ กราฟ โดยเน้นการประยุกต์ใช้ในด้านวิทยาการคอมพิวเตอร์'),
('', 'CS102', 'คพ.102', 'Problem Solving Basics and Computer Programming', 'พื้นฐานการแก้ปัญหาและการโปรแกรมคอมพิวเตอร์', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Algorithmic problem solving, structural design and programming, programming language syntax and semantics, data types, control structures, functions and parameter passing, recursive functions, testing and debugging.', 'การแก้ปัญหาด้วยวิธีการทางคอมพิวเตอร์ การออกแบบและการโปรแกรมเชิงโครงสร้าง ชนิดของข้อมูล โครงสร้างการควบคุม ฟังก์ชันและการส่งค่าพารามิเตอร์ ฟังก์ชันเวียนเกิด การทดสอบ และตรวจหาข้อผิดพลาด'),
('', 'CS103', 'คพ.103', 'Introduction to Computer Programming', 'การโปรแกรมคอมพิวเตอร์เบื้องต้น', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', '(No credit for Computer Science students and students who studied CS 102)\r\nIntroduction to algorithmic problem solving, structural design and programming, programming language syntax and semantics, data types, control structures, functions and\r\nparameter passing.', '(ไม่นับหน่วยกิตสำหรับนักศึกษาสาขาวิชาวิทยาการคอมพิวเตอร์และผู้ศึกษา คพ.102)\r\nแนวความคิดเบื้องต้นของการแก้ไขปัญหา การออกแบบ และการโปรแกรมเชิงโครงสร้างไวยากรณ์และความหมายของภาษาโปรแกรม ชนิดข้อมูล โครงสร้างการควบคุม ฟังก์ชันและการส่งค่าพารามิเตอร์\r\n'),
('', 'CS104', 'คพ.104', 'Introduction to Computer Programming using Python', 'การโปรแกรมคอมพิวเตอร์เบื้องต้นด้วยภาษาไพทอน', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', '(No credit for Computer Science students and students who studied CS 254)\r\nBasic computer programming and problem solving using Python. Structural design and Programming, basic data types. Control Structures. Functions, python built-in data\r\nstructures: lists, tuples, sets, dictionaries, and range, numerical processing library, arrays\r\nand matrix, library for Data Visualization.', '(ไม่นับหน่วยกิตสำหรับนักศึกษาสาขาวิชาวิทยาการคอมพิวเตอร์และผู้ศึกษา คพ.254)\r\nพื้นฐานการแก้ปัญหาด้วยวิธีการทางคอมพิวเตอร์ด้วยภาษาไพทอน การโปรแกรมเชิงโครงสร้างชนิดของข้อมูลพื้นฐาน โครงสร้างการควบคุม ฟังก์ชัน โครงสร้างข้อมูลพื้นฐาน ลิสต์ ทูเพิล เซ็ต ดิกชันนารี\r\nเรนจ์ ไลบราลีภาษาไพทอนส าหรับการประมวลผลเชิงตัวเลข อาร์เรย์และแมทริกซ์ไลบราลีภาษาไพทอนสำหรับแสดงข้อมูล'),
('', 'CS111', 'คพ.111', 'Object-Oriented Concepts', 'แนวคิดเชิงวัตถุ', 3, '(3-0-6)', '', 'คพ.101 และ คพ.102', 'CS101 and CS102', 'Developing of analytical and problem-solving skills through object-oriented\r\nparadigm. Integrating of conceptual and state-of-the-art practical approaches in software\r\ndevelopment life cycle (SDLC), object-oriented design techniques and tools, objectoriented programming based on the design, consistency verification between the design\r\nand source code.', 'พัฒนาทักษะการวิเคราะห์และการแก้ปัญหาด้วยแนวคิดเชิงวัตถุ บูรณาการแนวคิดและแนวทาง\r\nเชิงปฎิบัติที่ทันสมัยในวัฏจักรการพัฒนาซอฟต์แวร์ หลักการพื้นฐานในการเขียนโปรแกรมเชิงวัตถุตามที่\r\nวิเคราะห์และออกแบบไว้ แนวทางในการทวนสอบความสอดคล้องระหว่างแบบและซอร์สโค้ด'),
('', 'CS112', 'คพ.112', 'Introduction to Object-Oriented Programming', 'การโปรแกรมเชิงวัตถุเบื้องต้น', 3, '(3-0-6)', 'CS111', 'คพ.103', 'CS103', '(No credit for Computer Science students and students who studied CS 111)\r\nIntroduction to object-oriented programming, abstract data types, encapsulation,\r\ninheritance, polymorphism, and overloading. ', '(ไม่นับหน่วยกิตสำหรับนักศึกษาสาขาวิชาวิทยาการคอมพิวเตอร์ และผู้ศึกษา คพ.111)\r\nความรู้เบื้องต้นเกี่ยวกับการโปรแกรมเชิงวัตถุ ชนิดข้อมูลนามธรรม เอนแคปซูเลชัน การสืบทอด\r\nโพลีมอร์ฟิสซึม โอเวอร์โหลดดิง '),
('', 'CS201', 'คพ.201 ', 'Statistics and Research methodology for learning technology', 'สถิติและการวิจัยเพื่อเทคโนโลยีการเรียนรู้', 3, '(3-0-6)', '', 'ส.216', 'ST216', 'Fundamentals of research, research problem formulation design, and\r\nimplementation research for interactive multimedia learning, basic statistics to analyze\r\nresearch data, data preparation and analysis, interpretation result of data analysis,\r\nconclusion and discussion and writing a research report.', 'พื้นฐานการวิจัย การกำหนดปัญหาการวิจัยทางเทคโนโลยีการเรียนรู้ด้วยสื่อมัลติมีเดียเชิง\r\nปฏิสัมพันธ์ การออกแบบ การดำเนินการวิจัย สถิติพื้นฐานเพื่อการวิเคราะห์ข้อมูล การเตรียมข้อมูลและ\r\nการวิเคราะห์ข้อมูล การแปลผลการวิเคราะห์ข้อมูล การสรุปและอภิปรายผล และการเขียนรายงานการวิจัย'),
('', 'CS213', 'คพ.213', 'Data Structures', 'โครงสร้างข้อมูล', 3, '(3-0-6)', '', 'คพ.111 หรือ คพ.112', 'CS111 and CS112', 'Introduction to algorithm analysis, data abstraction, and fundamental data\r\nstructures including linear data structures and nonlinear data structures, dynamic storage\r\nallocation, searching and sorting techniques.', 'การวิเคราะห์ขั้นตอนวิธีเบื้องต้น หลักนามธรรมข้อมูล โครงสร้างข้อมูลพื้นฐานได้แก่ ข้อมูลเชิงเส้น\r\nและข้อมูลแบบไม่เชิงเส้น การจัดสรรหน่วยเก็บแบบพลวัต เทคนิคการค้นหา และการเรียงลำดับข้อมูลใน\r\nหน่วยความจำ การฝึกปฏิบัตินอกเวลา'),
('', 'CS216', 'คพ.216', 'Data Structures and Algorithms', 'โครงสร้างข้อมูลและขั้นตอนวิธี', 3, '(3-0-6)', '', 'คพ.111 หรือ คพ.112', 'CS111 and CS112', 'Analysis of running time and complexity of the algorithms, data structures: arrays, linked lists, stacks, queues, trees, hash, graph, binary heap, analysis of running time and memory requirements in searching, algorithms for searching and sorting, algorithm techniques: brute force, divide-and-conquer, greedy algorithms, space and time tradeoffs', 'การวิเคราะห์เวลาดำเนินงานและความซับซ้อนของขั้นตอนวิธี โครงสร้างข้อมูลแบบต่าง ๆ อาร์เรย์ลิงค์ลิสต์ สแตค คิว ทรี แฮช กราฟ ไบนารีฮีป การวิเคราะห์ความต้องการด้านเวลา และ หน่วยความจำในการค้นหา ขั้นตอนวิธีเกี่ยวกับการค้นหาและการเรียงลำดับ การแก้ปัญหาแบบบรูทฟอร์ซ การแบ่งแล้วเข้ายึด ขั้นตอนวิธีการแบบละโมบ การชดเชยกันระหว่างเวลากับเนื้อที่ของการคำนวณ\r\n'),
('', 'CS217', 'คพ.217', 'Design and Analysis of Algorithms', 'การออกแบบและวิเคราะห์ขั้นตอนวิธี', 3, '(3-0-6)', '', 'คพ.213', 'CS213', 'Techniques used in design and analysis of algorithms such as divide-and-conquer,\r\ngreedy algorithms, dynamic programming, graph traveling, backtracking, branch and\r\nbound. Study the topics of sorting, searching, Fourier transform, randomized algorithms,\r\ngraph algorithms and optimization methods.', 'เทคนิคต่างๆ ที่ใช้ในการออกแบบและวิเคราะห์ขั้นตอนวิธี ได้แก่ วิธีการแบ่งแยกเอาชนะ วิธีละโมบ วิธีก าหนดการพลวัต วิธีการแวะผ่านบัพทุกบัพของกราฟ วิธีการย้อนรอย และวิธีบรานช์แอนบาวด์ ตัวอย่างการใช้งานครอบคลุมวิธีการเรียงลำดับ และการค้นหาข้อมูล การแปลงฟูเรียร์ ขั้นตอนวิธีแบบสุ่มขั้นตอนวิธีต่างๆ สำหรับกราฟ ขั้นตอนการหาค่าที่ให้ประโยชน์สูงสุด'),
('', 'CS218', 'คพ.218', 'Operations Research for Computer Science', 'การวิจัยดำเนินการสำหรับวิทยาการคอมพิวเตอร์', 3, '(3-0-6)', '', 'คพ.101', 'CS101', 'Linear programming, simplex method, integer programming, introduction to heuristics, meta heuristics, applications or case studies in linear programming and integer programming models to solve real problems, and use of some optimization packages to solve for searching the best solution.', 'กำหนดการเชิงเส้น วิธีซิมเพล็กซ์ กำหนดการเชิงจำนวนเต็ม แนะนำฮิวริสติก เมต้าฮิวริสติการประยุกต์หรือกรณีศึกษำตัวแบบกำหนดการเชิงเส้นและกำหนดการเชิงจำนวนเต็มกับการแก้ปัญหาจริง การ\r\nใช้โปรแกรมสำเร็จรูปสำหรับแก้ปัญหาการค้นหาคำตอบที่ดีที่สุด\r\n'),
('', 'CS221', 'คพ.221', 'Introduction to Computer System and Organization', 'โครงสร้างและระบบคอมพิวเตอร์เบื้องต้น', 3, '(3-0-6)', '', '- คพ.101 และ คพ.102\r\nหรือ\r\n- คพ.101 และ คพ.103\r\nแบบใดแบบหนึ่ง', '- CS101 and CS102\r\nor\r\n- CS101 and CS103\r\nOne of the above.', 'Understanding of the internal structure and implementation of digital computers, computer boot up process, data representation and manipulation of atomic data, floating-point errors. The structure of a typical instruction set. The environment in which a program is compiled and executed. Computer Memory hierarchy, concepts for the hardware implementation of a processor: Combinatorial Circuits, Sequential Circuits, and Processor structure. Input/Output interfaces.', 'สาระสำคัญเกี่ยวกับโครงสร้างและการอิมพลีเมนต์ดิจิทัลคอมพิวเตอร์ กระบวนการบูตเครื่องคอมพิวเตอร์ ระบบแทนข้อมูลและการจัดการข้อมูลแบบครบหน่วย ข้อผิดพลาดเกี่ยวกับการจัดเก็บและประมวลผลเลขทศนิยม ชุดคำสั่ง การแปลและประมวลผลโปรแกรม ลำดับขั้นของหน่วยความจำในระบบคอมพิวเตอร์ พื้นฐานฮาร์ดแวร์ของหน่วยประมวลผล ได้แก่ วงจรรวม วงจรซีเควนเชียล และ แนวทางการสร้างหน่วยประมวลผลแบบง่าย การต่อเชื่อมกับอุปกรณ์ภายนอก'),
('', 'CS222', 'คพ.222', 'Operating Systems', 'ระบบปฏิบัติการ', 3, '(3-0-6)', '', 'คพ.213 และ คพ.221', 'CS213 and CS221', 'Basic concepts of operating systems design and implementation mutual exclusion, process management, memory management, file and device management, computer security and case studies.', 'พื้นฐานการออกแบบและการสร้างระบบปฏิบัติการ องค์ประกอบของระบบปฏิบัติการ การครอบครองเดี่ยว สมวาร โปรเซสและการจัดการ การจัดการหน่วยความจำ ระบบไฟล์ การจัดการอุปกรณ์ระบบความปลอดภัย กรณีศึกษา'),
('', 'CS233', 'คพ.233', 'Computer Architecture and Operating Systems', 'สถาปัตยกรรมคอมพิวเตอร์และระบบปฎิบัติการ', 3, '(3-0-6)', '', '- คพ.101 และ คพ.102\r\nหรือ\r\n- คพ.101 และ คพ.103\r\nแบบใดแบบหนึ่ง', '- CS101 and CS102\r\nหรือ\r\n- CS101 and CS103\r\nOne of the above.', 'Instruction set architectures (ISA), pipeline processing, multiprocessors, memory management, cache and virtual memory organization, process synchronization, CPU\r\nscheduling, multithreading, file system, input/output control and devices.', 'สถาปัตยกรรมชุดคำสั่ง การประมวลผลแบบสายท่อ มัลติโพรเซสเซอร์ การจัดการหน่วยความจำแคชและการ จัดระบบหน่วยความจ าเสมือน การประสานเวลาของโปรเซส การจัดตารางซีพียู มัลติเธรดดิ้ง ระบบไฟล์ การควบคุมอินพุตเอาท์พุตและอุปกรณ์'),
('', 'CS234', 'คพ.234', 'Computer Network and Security', 'ระบบเครือข่ายคอมพิวเตอร์และความปลอดภัย', 3, '(3-0-6)', '', 'คพ.233', 'CS233', 'Internet protocol including information security, digital signatures, digital certificates, malwares, security policies and models, security assurance, risk analysis, security administration of information systems.', 'ระบบเครือข่ายอินเทอร์เน็ต รวมถึงความปลอดภัยของสารสนเทศ ลายมือชื่อดิจิทัล ใบรับรองดิจิทัล โปรแกรมที่มีจุดประสงค์ร้าย นโยบายและแบบจำลองความปลอดภัย การรับรองความปลอดภัย การวิเคราะห์ความเสี่ยง การจัดการความปลอดภัยของระบบสารสนเทศ'),
('', 'CS241', 'คพ.241', 'Programming Languages and Paradigms', 'ภาษาโปรแกรมและกรอบความคิด', 3, '(3-0-6)', '', 'คพ.111 หรือ คพ.112', 'CS111 and CS112', 'Principles of programming languages, syntax and semantics. Different programming\r\nparadigms, performance-aware programming. Programming using Application Programming\r\nInterface (API), library for data manipulation event-driven programming.', 'หลักการของภาษาโปรแกรม ไวยกรณ์และวากยะสัมพันธ์ ศึกษากรอบแนวคิดของภาษาโปรแกรม\r\nประเภทต่างๆ การโปรแกรมโดยคำนึงถึงสมรรถนะ การโปรแกรมโดยอาศัยส่วนต่อประสานโปรแกรม\r\nประยุกต์ ไลบรารี่สำหรับจัดการข้อมูล และการโปรแกรมเชิงเหตุการณ์'),
('', 'CS245', 'คพ.245', 'Principles of Data Science', 'หลักการวิทยาการข้อมูล', 3, '(3-0-6)', '', 'ส.216 หรือ ส.211', 'ST216 and ST211', 'Fundamental principles of data science including algorithms, processes, methods,\r\ndata-analytic thinking and tools to support problem-focused data-analytic thinking.\r\nIntroduction to topics in data science: Data Manipulation, Data Analysis with Statistics and\r\nMachine Learning, Data Communication with Information Visualization, and Data at Scale.', 'หลักการพื้นฐานของวิทยาการข้อมูลที่เกี่ยวข้องกับอัลกอริทึม กระบวนการ วิธีการและหลักการคิด\r\nรวมทั้งเครื่องมือที่ใช้ในการวิเคราะห์ข้อมูล หัวข้อพื้นฐานในวิทยาการข้อมูล ได้แก่ การจัดการข้อมูล การ\r\nวิเคราะห์ข้อมูลเชิงสถิติ และเชิงการเรียนรู้ของเครื่องจักร การนำเสนอข้อมูลด้วยทัศนสารสนเทศและการทำงานกับข้อมูลขนาดใหญ่'),
('', 'CS246', 'คพ.246', 'Data Visualization', 'การแสดงข้อมูล', 3, '(3-0-6)', '', 'คพ.245', 'CS245', 'This course focuses on the design implementation and evaluation of complementary visual and verbal representations of patterns, and learn how to acquire, parse, and analyze large datasets in order to convey findings answer questions, drive decisions, and provide persuasive evidence supported by data.', 'หลักการออกแบบ พัฒนาและการประเมินการแสดงข้อมูล การได้มา การแยก และการวิเคราะห์ ข้อมูลขนาดใหญ่ เทคนิคและเครื่องมือส าหรับข้อมูลรูปแบบต่างๆ เพื่อสื่อสารสิ่งที่ค้นพบหรือคำตอบของปัญหา สำหรับสนับสนุนการตัดสินใจ'),
('', 'CS251', 'คพ.251', 'Database Systems 1', 'ระบบฐานข้อมูล 1', 3, '(3-0-6)', '', 'คพ.213 หรือ คพ.216', 'CS213 or CS216', 'Fundamental database concepts and architecture, conceptual data models, design and implementation, query languages, metadata, physical data storage, file organizations, and introduction to transaction management.', 'แนวคิดพื้นฐานและสถาปัตยกรรมของระบบฐานข้อมูล การจำลองข้อมูลเชิงแนวคิด การออกแบบฐานข้อมูลและการทำให้เกิดผล ภาษาสอบถาม เมตาเดตา การจัดระเบียบแฟ้มและหน่วยเก็บข้อมูลเชิงกายภาพ แนะนำการจัดการรายการเปลี่ยนแปลง มีฝึกปฏิบัตินอกเวลา'),
('', 'CS253', 'คพ.253', 'Computer Programming for Business', 'การเขียนโปรแกรมสำหรับธุรกิจ', 3, '(3-0-6)', '', 'คพ.102 หรือ คพ.103', 'CS102 and CS103', 'Computer programming to solve business problems, algorithm design and implementation via programming paradigm and tools suitable for business problems domain, testing and debugging, basic graphical user interface development, event-driven programming.', 'การแก้ปัญหาทางธุรกิจแบบเบื้องต้นด้วยวิธีการทางคอมพิวเตอร์ การออกแบบและพัฒนาอัลกอริทึมด้วยเทคนิคและเครื่องมือทางคอมพิวเตอร์ที่เหมาะสมกับปัญหาทางธุรกิจ การทดสอบ และตรวจหาข้อผิดพลาด การพัฒนาส่วนต่อประสานผู้ใช้เชิงกราฟิกเบื้องต้น การพัฒนาโปรแกรมเชิงเหตุการณ์'),
('', 'CS254', 'คพ.254', 'Computer Programming using Python', 'การเขียนโปรแกรมด้วยภาษาไพทอน', 3, '(3-0-6)', '', 'คพ.111 หรือ คพ.112', 'CS111 and CS112', 'Computer programming and problem solving using python, structural design and Programming, basic data types, control Structures, functions. Recursions, python built-in data structures: lists, tuples, sets, dictionaries, and range, testing and debugging, objectoriented programming using python, class, methods, numerical processing library, arrays and matrix, library for data visualization, introduction to library for data analytics.\r\n', 'การแก้ปัญหาด้วยวิธีการทางคอมพิวเตอร์ด้วยภาษาไพทอน การโปรแกรมเชิงโครงสร้าง ชนิดของข้อมูลพื้นฐาน โครงสร้างการควบคุม ฟังก์ชัน ฟังก์ชันเวียนเกิด โครงสร้างข้อมูลพื้นฐาน ลิสต์ ทูเพิล เซ็ต ดิกชันนารี เรนจ์ การทดสอบ ตรวจหาข้อผิดพลาด การโปรแกรมเชิงวัตถุด้วยภาษาไพทอน คลาส เมธอด ไลบราลีภาษาไพทอนส าหรับการประมวลผลเชิงตัวเลข อาร์เรย์และแมทริกซ์ไลบราลีภาษาไพทอนสำหรับ\r\nแสดงข้อมูล พื้นฐานการใช้งานไลบราลีภาษาไพทอนสำหรับการวิเคราะห์ข้อมูล'),
('', 'CS262', 'คพ.262', 'Introduction to Software Testing', 'การทดสอบซอฟต์แวร์เบื้องต้น', 3, '(3-0-6)', '', 'คพ.111 หรือ คพ.112', 'CS111 and CS112', 'Software testing and quality assurance concepts, test data generation using whitebox and black-box techniques, software testing at unit, module, sub-system, and system levels, and software testing process and planning.', 'แนวคิดการทดสอบและการประกันคุณภาพซอฟต์แวร์ เทคนิคการสร้างข้อมูลการทดสอบแบบแบลคบอกซ์และไวท์บอกซ์ การทดสอบซอฟต์แวร์ในระดับยูนิต โมดูล ระบบย่อย และทั้งระบบกระบวนการทดสอบและการวางแผนการทดสอบซอฟต์แวร์'),
('', 'CS264', 'คพ.264', 'Introduction to Software Engineering', 'วิศวกรรมซอฟต์แวร์เบื้องต้น', 3, '(3-0-6)', '', 'คพ.111 หรือ คพ.112', 'CS111 and CS112', 'Fundamental of software engineering principles, software development methodology, software process models, basics of software project planning and project management, basics of time and cost estimation, requirement elicitation and specification, software analysis and design, concept of software architecture, software construction techniques including design pattern, component-oriented development, basics of verification and validation, software evolution, software development environment, and sample of CASE tools.\r\n', 'คุณลักษณะซอฟต์แวร์ คุณภาพของซอฟต์แวร์และโครงการซอฟต์แวร์ หลักการของวิศวกรรมซอฟต์แวร์ ระเบียบวิธีในการพัฒนาซอฟต์แวร์ กระบวนการพัฒนาซอฟต์แวร์ที่ส าคัญ การวางแผนและจัดการโครงการ การประเมินเวลาและค่าใช้จ่าย วิเคราะห์และการระบุข้อก าหนด เทคนิคการวิเคราะห์และออกแบบซอฟต์แวร์ แนะน าสถาปัตยกรรมซอฟต์แวร์ เทคนิคการพัฒนาโปรแกรม การตรวจสอบและการทวนสอบซอฟต์แวร์ วิวัฒนาการของซอฟต์แวร์ สภาพแวดล้อมการผลิตซอฟต์แวร์และเครื่องมือช่วยจัดการโครงการ กรณีศึกษา มีฝึกปฏิบัตินอกเวลา'),
('', 'CS265', 'คพ.265', 'Artificial Intelligence Fundamentals', 'ปัญญาประดิษฐ์เบื้องต้น', 3, '(3-0-6)', '', 'คพ.213 หรือ คพ.216', 'CS213 or CS216', 'Problems in artificial intelligent systems, knowledge representation, uniform search, inform search, constraint-based problems, logics and automatic reasoning, game theory, introduction to machine learning', 'ปัญหาทางปัญญาประดิษฐ์ การแทนความรู้ การค้นหาแบบไม่มีข้อมูล การค้นหาแบบมีข้อมูลปัญหาการทำตามเงื่อนไข ตรรกศาสตร์และการให้เหตุผลอัตโนมัติ ทฤษฎีเกม การเรียนรู้ของเครื่องจักรเบื้องต้น '),
('', 'CS266', 'คพ.266', 'Software Process and Quality Assurance', 'กระบวนการซอฟต์แวร์และการประกันคุณภาพ', 3, '(3-0-6)', '', 'คพ.264', 'CS264', 'Study essential components of software process including activities, methods, and practices used to develop and maintain software development including its work products. Introduce basic knowledge of process and product quality assurance, how to define quality for measures and measurement.', 'องค์ประกอบของกระบวนการซอฟต์แวร์ครอบคลุม กิจกรรม วิธีการ และวิธีปฏิบัติที่ใช้ เพื่อพัฒนาและบำรุงรักษาซอฟต์แวร์ รวมถึงชิ้นงานอื่นๆที่เกี่ยวข้องกับการพัฒนาซอฟต์แวร์ แนะนำหลักการเบื้องต้นของการประกันคุณภาพของกระบวนการพัฒนาซอฟต์แวร์ และตัวซอฟต์แวร์ แนะนำการใช้ร่วมกับความรู้เบื้องต้นในการนิยามสำหรับตัววัด และการวัด'),
('', 'CS267', 'คพ.267', 'Software Requirement Specification and Management', 'การกำหนดและการจัดการความต้องการทางซอฟต์แวร์', 3, '(3-0-6)', '', 'คพ.264', 'CS264', 'Quantify many aspects of requirement processes include eliciting, analyzing, negotiating, specifying, validating and basic principle of managing requirements introduce methods, techniques and tools used to define, document and ensure customer satisfaction.', 'กระบวนการในการหาความต้องการในหลายรูปแบบได้แก่ การสืบค้น การวิเคราะห์ การหาข้อตกลง การระบุข้อกำหนด การทวนสอบ และหลักการเบื้องต้นของการบริหารจัดการความต้องการศึกษาระเบียบวิธี แนะนำเทคนิคและเครื่องมือที่จะนำไปใช้เพื่อนิยาม สร้างเอกสาร และประกันความพึงพอใจของลูกค้า'),
('', 'CS285', 'คพ.285', 'Human Information Processing', 'การประมวลสารสนเทศของมนุษย์', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Introduction to research and theory on topics in human information processing including perception, attention, pattern recognition, memory, representation of knowledge, language, problem solving, reasoning, and learning, with emphasis on the relationship to computer models of these processes and implications of this body of knowledge for building information systems.', 'งานวิจัยและทฤษฎีเบื้องต้นเกี่ยวกับการประมวลผลสารสนเทศของมนุษย์ ความใส่ใจ การรู้จำแบบความจำ การแทนองค์ความรู้และภาษา กระบวนการแก้ไขปัญหา กระบวนการหาเหตุผล และกระบวนการเรียนรู้ ความสัมพันธ์ระหว่างกระบวนการรู้จำของมนุษย์กับต้นแบบทางคอมพิวเตอร์ และการประมวลนัยสำคัญของเนื้อหาเกี่ยวกับการรู้จำเพื่อสร้างระบบสารสนเทศ'),
('', 'CS299', 'คพ.299', 'Computer Graphics 1', 'คอมพิวเตอร์กราฟิก 1', 3, '(3-0-6)', '', 'คพ.111 หรือ คพ.112', 'CS111 or CS112', 'Software and hardware principles of interactive graphics, general methods for designing and displaying output, elementary operations in two-and three-dimensional space, transformational geometry, viewing transformations, clipping, color theory.', 'ซอฟต์แวร์และฮาร์ดแวร์ ส าหรับคอมพิวเตอร์กราฟิกแบบโต้ตอบ วิธีการทั่วไปที่ใช้ในการออกแบบ และแสดงผลภาพ การดำเนินการพื้นฐานในปริภูมิ 2 มิติและ 3 มิติ การแปลงในระบบเรขาคณิต การแปลงจุดหรือตำแหน่งที่มองเห็น การตัดภาพ ทฤษฎีสี มีฝึกปฏิบัตินอกเวลา'),
('', 'CS300', 'คพ.300', 'Seminar in Practical Programming', 'สัมมนาการโปรแกรมภาคปฏิบัต', 1, '(1-0-3)', '', 'คพ.111', 'CS111', 'Seminar of design and practical programming with structural and object-oriented paradigms as qualification for special topics in computer science. Measurement and evaluation in this course can results in two levels: “S” (Satisfactory) and “U” (Unsatisfactory).', 'สัมมนา การออกแบบและการโปรแกรมคอมพิวเตอร์เชิงโครงสร้างและเชิงวัตถุเพื่อการแก้ไขปัญหาให้ปฏิบัติได้จริงสำหรับปัญหาพิเศษทางวิทยาการคอมพิวเตอร์ การวัดผลแบ่งเป็น 2 ระดับ คือ ระดับ S (ใช้ได้) และ ระดับ U (ยังใช้ไม่ได้)'),
('', 'CS301', 'คพ.301', 'Computer Science Project Proposal and Presentation', 'ข้อเสนอและการนำเสนอโครงงานทางวิทยาการคอมพิวเตอร์ ', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Critical thinking, information searching techniques, analysis and planning for computer science projects, teamwork, academic writing styles, citation and bibliography and presentation techniques.', 'การคิดเชิงวิพากษ์ การสืบค้น การวางแผน และการทำงานเป็นทีมในการดำเนินโครงงานทางวิทยาการคอมพิวเตอร์รูปแบบการเขียนรายงาน การอ้างอิงเชิงวิชาการรวมถึงเทคนิคการนำเสนอ'),
('', 'CS302', 'คพ.302', 'Co-operative Education Preparations', 'การเตรียมความพร้อมสำหรับสหกิจศึกษา', 3, '(1-4-5)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Preparing students skills for work, application and resume writing, interview, critical thinking, searching techniques, participating in software development teams, presentation and organization communication.', 'ฝึกฝนทักษะที่จำเป็นต้องใช้ในการทำงาน การเขียนใบสมัครงาน การเขียนประวัติ การสัมภาษณ์ การคิดเชิงวิพากษ์ การสืบค้นข้อมูลเพื่อประกอบการทำงาน การทำงานเป็นทีมในการพัฒนาซอฟต์แวร์การนำเสนอ รวมถึงเทคนิคการเจรจาสื่อสารภายในองค์กร'),
('', 'CS303', 'คพ.303', 'Special Projects 1', 'โครงงานพิเศษ 1', 2, '(0-6-0)', '', 'คพ.300 และ ( คพ.301 หรือ คพ.302 )', 'CS300 and ( CS301 or CS302 )', 'Senior Projects will be assigned or approved by the department. This course prepares students for developing a proposal for doing research, writing research papers, and presenting the proposal to the committee. ', 'โครงงานการศึกษาจะก าหนดหรือได้รับอนุมัติจากสาขาวิชาศึกษาหัวข้อทางวิชาการ โดยมีวัตถุประสงค์ให้นักศึกษาค้นคว้าทางวิชาการ เขียนรายงาน และเสนอต่อคณะกรรมการ'),
('', 'CS304', 'คพ.304', 'Co-operative Education 1', 'สหกิจศึกษา 1', 2, '(0-6-0)', '', 'คพ.302', 'CS302', 'Supervised practical training on the given assignments from authorized body from the faculty. Student must show the capability in implementation of knowledge and skill in the actual working environmemt. Written report of design, development, and implementation must be submitted the end of practical period.', 'การปฏิบัติงานที่ได้รับมอบหมายจากสถานประกอบการที่ได้รับความเห็นชอบจากสาขาวิชา โดยนักศึกษาต้องนำความรู้ทางวิชาการที่ได้เรียนไปประยุกต์ใช้และฝึกทักษะในภาวะแวดล้อมการทำงานจริงภายใต้การกำกับดูแลของสถาน ประกอบการนั้น โดยต้องแสดงงานที่ได้รับมอบหมายอย่างชัดเจนพร้อมทั้งแนวคิดที่ ใช้ในการออกแบบ พัฒนาและประยุกต์ เมื่อเสร็จสิ้นโครงงานแล้วต้องจัดส่งผลงานในรูปแบบของรายงานตามที่สาขาวิชากำหนด'),
('', 'CS305', 'คพ.305', 'Social and Professional Ethics', 'จรรยาบรรณทางวิชาชีพและเชิงสังคม', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Social context of computing, methods and tools of analysis, professional and ethical responsibilities, intellectual property, risks and liabilities of computer-based systems, privacy and civil liberties, intellectual property infringement, computer crime in computing.\r\n', 'บริบททางสังคมของระบบคอมพิวเตอร์วิธีการและเครื่องมือในการวิเคราะห์ความรับผิดชอบและจรรยาบรรณทางวิชาชีพ กฎหมายทรัพย์สินทางปัญญาการยอมรับความเสี่ยงและการชดใช้ต่อระบบคอมพิวเตอร์การละเมิดทรัพย์สินทางปัญญา การละเมิดสิทธิส่วนบุคคลอาชญากรรมในระบบคอมพิวเตอร์'),
('', 'CS311', 'คพ.311', 'Learning Measurement and Evaluation', 'การวัดและประเมินผลการเรียนรู้', 3, '(3-0-6)', '', 'คพ.201', 'CS201', 'Significance of measurement and evaluation in learning, principles and techniques of learning measurement and evaluation, development and use of measurement and evaluation tools, application of learning measurement and evaluation result in learning through multimedia, basic statistics and software for measurement and evaluation of learning', 'ความสำคัญของวัดผลและการประเมินผลการเรียนรู้ หลักการและเทคนิควัดและประเมินผลการเรียนรู้ การพัฒนาและใช้เครื่องมือการัดและประเมินผลการเรียนรู้ การน าผลการประเมินไปประยุกต์ใช้ในการปรับปรุง การออกแบบการเรียนรู้ผ่านสื่อเทคโนโลยี สถิติและโปรแกรมคอมพิวเตอร์ที่ใช้ในการวัดและประเมินผลการเรียนรู้'),
('', 'CS312', 'คพ.312', 'Learning Principles for Interactive multimedia', 'หลักการเรียนรู้เพื่อเทคโนโลยีการเรียนรู้', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Principles and theory of learning, learning process, type of learning, teaching and learning problems, factors influencing learning, motivation, and application to interactive multimedia design and enhance learning.\r\n', 'หลักและทฤษฎีการเรียนรู้ กระบวนการเรียนรู้ ชนิดการเรียนรู้ ปัญหาในการเรียนการสอน ปัจจัยที่ส่งผลต่อการเรียนรู้ การจูงใจ และการประยุกต์เพื่อการออกแบบมัลติมีเดียเชิงปฏิสัมพันธ์ และการส่งเสริมการเรียนรู้ '),
('', 'CS314', 'คพ.314', 'Automata Theory', 'ทฤษฎีออโตมาตา', 3, '(3-0-6)', '', 'คพ.241', 'CS241', 'Fundamentals of abstract machine and language, automata theory, regular expression, regular language, pushdown automata, context-free language, Turing machine, the halting problem, undecidability and intractability', 'มูลฐานของเครื่องจักรนามธรรมและภาษา ทฤษฎีออโตมาตา นิพจน์แบบเรกูลาร์ ภาษาแบบเรกูลาร์ ออโตมาตาแบบกดลง ภาษาไม่พึ่งบริบท เครื่องจักรทัวริง ปัญหาการหยุด ความสามารถและประสิทธิภาพในการแก้ปัญหาของเครื่องคอมพิวเตอร์'),
('', 'CS319', 'คพ.319', 'Selected Topics in Computer Science', 'หัวข้อเลือกสรรทางวิทยาการคอมพิวเตอร์', 3, '(3-0-6)', '', 'คพ.111 หรือ คพ.112', 'CS111 or CS112', 'Topics selected from areas in Computer Science, keep up with the new technology and knowledge', 'หัวข้อเลือกสรรจากความก้าวหน้าด้านงานวิจัยและเทคโนโลยีของวิทยาการคอมพิวเตอร์ ที่เปลี่ยนแปลงตามยุคสมัยและเทคโนโลย'),
('', 'CS320', 'คพ.320', 'Selected Topics in Computer Architecture', 'หัวข้อเลือกสรรด้านสถาปัตยกรรมคอมพิวเตอร์', 3, '(3-0-6)', '', 'คพ.221', 'CS221', 'Seminar on current research and development in computer architecture.', 'หัวข้อเลือกสรรจากความก้าวหน้าด้านงานวิจัยและเทคโนโลยีของสถาปัตยกรรมคอมพิวเตอร์ที่เปลี่ยนแปลงตามยุคสมัยและเทคโนโลยี'),
('', 'CS322', 'คพ.322', 'Net-Centric Computing', 'คอมพิวเตอร์เครือข่าย', 3, '(3-0-6)', '', 'คพ.222', 'CS222', 'Basic network components and major network standards for computer communications via the Internet. The OSI layered model. The TCP/IP layered model. Basic functions of each layer. Major network protocols in each layers and their interoperability, socket programming.', 'องค์ประกอบหลักและมาตรฐานเครือข่ายสำหรับการโอนถ่ายข้อมูลผ่านระบบเครือข่ายอินเทอร์เน็ต แบบจำลองแบบลำดับขั้นโอเอสไอ แบบจำลองแบบลำดับขั้นทีซีพี/ไอพี หน้าที่หลักของแต่ละลำดับขั้นโปรโตคอลหลักในแต่ละลำดับขั้นและการทำงานร่วมกัน การเขียนโปรแกรมซ็อกเก็ต'),
('', 'CS324', 'คพ.324', 'Computer Security', 'ความปลอดภัยของระบบคอมพิวเตอร์', 3, '(3-0-6)', '', 'คพ.222', 'CS222', 'Security of information, computer systems, databases, networks and communications, symmetric and asymmetric cryptography, digital signatures, digital certificates, malwares, security policies and models, security assurance, risk analysis, security administration of information systems.', 'ความปลอดภัยของสารสนเทศ ระบบคอมพิวเตอร์ ฐานข้อมูล เครือข่ายและการสื่อสาร การเข้ารหัสแบบสมมาตรและอสมมาตร ลายมือชื่อดิจิทัล ใบรับรองดิจิทัล โปรแกรมที่มีจุดประสงค์ร้ายนโยบายและแบบจำลองความปลอดภัย การรับรองความปลอดภัย การวิเคราะห์ความเสี่ยง การจัดการความปลอดภัยของระบบสารสนเทศ'),
('', 'CS325', 'คพ.325', 'Practical Computer Networking', 'เครือข่ายคอมพิวเตอร์ภาคปฏิบัติ', 3, '(3-0-6)', '', 'คพ.322 หรือ คพ.334', 'CS322 or CS334', 'Advanced knowledge and hands-on experience in computer communications and networking, basic router, switch, and end-host onfigurations, internet protocol version 6 (Ipv6). IP addressing, network address translation (NAT), dynamic host configuration protocol (DHCP), switched networks, virtual LAN (VLAN), inter VLAN routing, routing protocols, basic network security, access control List (ACL).', 'ความรู้ขั้นสูงเกี่ยวกับการสื่อสารผ่านเครือข่ายคอมพิวเตอร์ ทักษะการต่อเชื่อมและการตั้งค่าอุปกรณ์ภายในระบบเครือข่าย การตั้งค่าอุปกรณ์เครือข่ายหลักได้แก่ เราท์เตอร์ สวิตช์ และระบบปลายทาง ไอพีโพรโทคอลเวอร์ชัน 6 การจัดแบ่งเลขที่อยู่แบบไอพี เทคนิคการแปลงหมายเลขไอพี(แนท) โพรโทคอลสนับสนุนการตั้งค่าก าหนดที่โฮสต์แบบพลวัตร (ดีเอชซีพี) สวิตช์เน็ตเวิร์ก ข่ายงานบริเวณเฉพาะที่แบบเสมือน การค้นหาเส้นทางระหว่างข่ายงานเฉพาะที่แบบเสมือน โพรโทคอลค้นหาเส้นทาง การป้องกันการโจมตีระบบคอมพิวเตอร์ผ่านทางเครือข่ายเบื้องต้น การควบคุมการผ่านเข้าออก'),
('', 'CS326', 'คพ.326', 'Embedded Systems Design', 'การออกแบบระบบฝังตัว', 3, '(3-0-6)', '', 'คพ.221', 'CS221', 'Design and implementation of integrated hardware and software for embedded systems to meet specifications/constraints, applications of embedded systems and related research.', 'การออกแบบให้องค์ประกอบฮาร์ดแวร์และซอฟต์แวร์ท างานร่วมกันในระบบฝังตัว เป็นการออกแบบระบบที่เป็นการใช้งานแบบจำเพาะเจาะจง การพิจารณาลักษณะการใช้งานต่างๆ รวมถึงงานวิจัยที่เกี่ยวข้อง\r\n'),
('', 'CS327', 'คพ.327', 'Parallel Computing', 'การคำนวณเชิงขนาน', 3, '(3-0-6)', '', 'คพ.222', 'CS222', 'Motivations and applications of parallel computing, parallel computer architecture, Theory and practice of parallelizing serial computations, parallel programming for shared-memory multiprocessors, distributed-memory multiprocessors, and graphical processing units, performance issues covering speedup, efficiency, scalability and overhead analysis.', 'วัตถุประสงค์และการใช้งานการคำนวณเชิงขนาน สถาปัตยกรรมของคอมพิวเตอร์เชิงขนาน ทฤษฎีและฝึกทักษะเกี่ยวกับการแปลงงานคำนวณแบบลำดับเป็นแบบขนาน การเขียนโปรแกรมเชิงขนานสำหรับเครื่องมัลติโพรเซสเซอร์แบบร่วมใช้หน่วยความจำและแบบหน่วยความจำกระจาย การสร้างโปรแกรมแบบขนานสำหรับหน่วยประมวลผลกราฟิก และประเด็นเกี่ยวกับประสิทธิภาพ ได้แก่การวิเคราะห์ อัตราความเร็วขึ้น ประสิทธิภาพ ความสามารถในการปรับขนาด และเวลาสูญเปล่า'),
('', 'CS328', 'คพ.328', 'Parallel Algorithm Designs', 'การออกแบบขั้นตอนวิธีแบบขนาน', 3, '(3-0-6)', '', 'คพ.217 และ คพ.222', 'CS217 and CS222', 'Principles of task decomposition, task-processor mapping techniques for load balancing, methods for minimizing interaction overheads, parallel algorithm design models (including data-parallel, work-pool, task graph, master-slave, pipeline, and hybrid models), and examples of parallel algorithms.', 'หลักการแยกงาน เทคนิคการจ่ายงานไปยังหน่วยประมวลผลเพื่อสร้างสมดุลของภาระงาน วิธีการลดค่าใช้จ่ายในการสื่อสารระหว่างงานให้ต่ำที่สุด โมเดลในการออกแบบขั้นตอนวิธีแบบขนาน ได้แก่ โมเดลแบ่งข้อมูลแบบขนาน โมเดลรวมกลุ่มงาน โมเดลกราฟงาน โมเดลหัวหน้าลูกน้อง ไพพ์ไลน์ และโมเดลผสมผสาน ตัวอย่างขั้นตอนวิธีแบบขนาน'),
('', 'CS329', 'คพ.329', 'Introduction to Modeling and Simulation', 'การสร้างโมเดลและการจำลองสถานการณ์เบื้องต้น', 3, '(3-0-6)', '', 'ส.216 และ คพ.213', 'ST216 and CS213', 'Queuing model, basics of modeling, simulation principles and analysis methodologies focusing on discrete-event simulation, simulation tools and conducting studies to address research issues for complex computer systems, model verification and statistical issues in analyzing simulation results.', 'ทฤษฎีคิว พื้นฐานของการสร้างโมเดล หลักการจำลองสถานการณ์ และระเบียบวิธีการวิเคราะห์ โดยเน้นที่การจำลองสถานการณ์แบบเหตุการณ์ไม่ต่อเนื่อง เครื่องมือเพื่อการจำลองสถานการณ์และดำเนินการศึกษาเพื่อแก้ไขปัญหาวิจัยที่เกิดขึ้นในระบบคอมพิวเตอร์ที่มีความซับซ้อน การตรวจสอบโมเดลและประเด็นเชิงสถิติในการวิเคราะห์ผลลัพธ์จากการจำลองสถานการณ์'),
('', 'CS330', 'คพ.330', 'Selected Topics in Net-Centric Computing', 'หัวข้อเลือกสรรด้านคอมพิวเตอร์เครือข่าย', 3, '(3-0-6)', '', 'คพ.322 หรือ คพ.334', 'CS322 or CS334', 'Seminar on current research and development in computer and telecommunication networking.', 'หัวข้อเลือกสรรจากความก้าวหน้าด้านงานวิจัยและเทคโนโลยีของระบบเครือข่าย ที่เปลี่ยนแปลงตามยุคสมัยและเทคโนโลยี'),
('', 'CS331', 'คพ.331', 'Wireless Network Technology', 'เทคโนโลยีเครือข่ายไร้สาย', 3, '(3-0-6)', '', 'คพ.322 หรือ คพ.334', 'CS322 or CS334', 'Overview of mobile communications and wireless networks, wireless transmission basis, multiple access control techniques, mobile telephone systems, wireless LAN. Mobile IP, Bluetooth, zigbee. WiMAX, wireless network security. ', 'ภาพรวมของการสื่อสารเคลื่อนที่และเครือข่ายไร้สาย พื้นฐานการส่งข้อมูลแบบไร้สาย เทคนิคการควบคุมการเข้าถึงพร้อมกันหลายทาง ระบบโทรศัพท์เคลื่อนที่ เทคโนโลยีของระบบแลนไร้สาย (มาตรฐาน IEEE 802.11) โมบายไอพีเทคโนโลยีบลูทูท เทคโนโลยีซิกบี เทคโนโลยีเซ็นเซอร์ไร้สาย ไวแมกซ์ ความปลอดภัยบนเครือข่ายไร้สาย'),
('', 'CS332', 'คพ.332', 'Introduction to Cloud Computing Technology', 'เทคโนโลยีกลุ่มเมฆเบื้องต้น', 3, '(3-0-6)', '', 'คพ.322 หรือ คพ.334', 'CS322 or CS334', 'Cloud computing concepts and characteristics, cloud computing service models e.g. Infrastructure as a Service (IaaS), Platform as a Service (PaaS), and software as a service (SaaS), cloud application development, cloud security', 'คุณลักษณะของการประมวลผลแบบกลุ่มเมฆ รูปแบบการให้บริการของการประมวลผลแบบกลุ่มเมฆ เช่น ไอเอเอเอส พีเอเอเอส และเอสเอเอเอส ทักษะการพัฒนาแอพพลิเคชันเพื่อให้บริการผ่านเทคโนโลยีกลุ่มเมฆ การรักษาความปลอดภัยบนกลุ่มเมฆ'),
('', 'CS333', 'คพ.333', 'Scalable Internet Services Architecture', 'สถาปัตยกรรมบริการอินเทอร์เน็ตที่ปรับขนาดได้', 3, '(3-0-6)', '', 'คพ.332', 'CS332', 'Fundamentals of architecting and building IT infrastructure on Cloud Platform for flexible and scalable Internet services, techniques and technologies of vertical and horizontal scaling, load balancing, data replication and sharding, user account management, system security, performance monitoring, best practices and recommended design patterns, case studies.', 'การออกแบบสถาปัตยกรรมและสร้างระบบโครงสร้างพื้นฐานสารสนเทศบนแพลตฟอร์มการประมวลผลแบบกลุ่มเมฆ เพื่อให้บริการประมวลผลบนอินเทอร์เน็ตที่มีความยืดหยุ่นและสามารถปรับขนาดได้ เทคนิควิธีและเทคโนโลยีต่างๆ ที่ใช้ ในการปรับขนาดได้แบบแนวตั้งและแนวนอน การแบ่งและกระจายงานในกลุ่มเครือข่ายของเครื่องแม่ข่าย ระบบ การสำเนาและแบ่งข้อมูลเก็บเป็นส่วนๆ การบริหารจัดการบัญชีผู้ใช้ ความปลอดภัยระบบ และการเฝ้าสังเกตประสิทธิภาพการทำงานของระบบ แนวปฏิบัติที่ดีและรูปแบบการออกแบบแนะนำ กรณีศึกษา'),
('', 'CS334', 'คพ.334', 'Computer Networks and Operating Systems', 'คอมพิวเตอร์เครือข่ายและระบบปฏิบัติการ', 3, '(3-0-6)', '', 'คพ.213', 'CS213', 'Overview of the key protocols and the architecture of the Internet. Introduction to modern operating system design, including memory management, scheduling, and Input/Output. The architecture of Unix-like operating systems is used as an example of more general principles in OS design.', 'ภาพรวมสถาปัตยกรรมและโพรโทคอลส าคัญของระบบเครือข่ายอินเทอร์เน็ต เบื้องต้นเกี่ยวกับองค์ประกอบหลักของระบบปฏิบัติการร่วมสมัย ได้แก่ การจัดการหน่วยความจำ การจัดล าดับงาน การรับเข้าและส่งออก ใช้ตัวอย่างจากสถาปัตยกรรมของกลุ่มระบบปฏิบัติการที่คล้ายคลึงกับระบบปฏิบัติการยูนิกซ์'),
('', 'CS335', 'คพ.335', 'Computer Architecture', 'สถาปัตยกรรมคอมพิวเตอร์', 3, '(3-0-6)', '', 'คพ.222', 'CS222', 'Topics in Computer System Performance. Advanced concepts in designing computer processors: Pipelining, Static and Dynamic scheduling, Superscalar and Vector executions. Advanced concepts in Computer Memory Hierarchy: Cache optimization and Virtual memory. Multi-processors and Cache coherence.', 'หัวข้อเกี่ยวกับสมรรถนะของระบบคอมพิวเตอร์ หัวข้อขั้นสูงเกี่ยวกับการออกแบบหน่วยประมวลผล ได้แก่ ไพพ์ไลนิง การจัดล าดับงานแบบสถิตและแบบพลวัตร การประมวลผลซูเปอร์สเกลาและเวกเตอร์ หัวข้อขั้นสูงเกี่ยวกับล าดับขั้นของหน่วยความจำในระบบคอมพิวเตอร์ ได้แก่ การเพิ่มประสิทธิภาพของแคช และ หน่วยความจำเสมือน มัลติโพรเซสเซอร์และแคชโคฮีเรนต์'),
('', 'CS337', 'คพ.337', 'Introduction to Cluster Computing and Distributed Computing', 'ระบบคลัสเตอร์คอมพิวเตอร์และการประมวลผลแบบกระจายเบื้องต้น', 3, '(3-0-6)', '', 'คพ.222 หรือ คพ.334', 'CS222 or  CS334', 'Study the construction of Beowulf and cluster computers, building a small cluster, using cluster installation and configuration tools, cluster monitoring, job scheduling, user management, cluster systems maintenance, security measures and policies', 'การสร้างระบบคลัสเตอร์หรือบีวูฟ การทดลองสร้างระบบคลัสเตอร์อย่างง่ายๆ การติดตั้งซอฟต์แวร์ที่ใช้ส าหรับบริหารจัดการระบบคลัสเตอร์ การมอนิเตอร์ระบบฯ การกำหนดตารางการทำงานของโพรเซสเซอร์ในระบบการบริหารจัดการผู้ใช้ การดูแลระบบคลัสเตอร์ การรักษาความปลอดภัย'),
('', 'CS339', 'คพ.339', 'Selected Topics in Operating Systems', 'หัวข้อเลือกสรรด้านระบบปฏิบัติการ', 3, '(3-0-6)', '', 'คพ.222 หรือ คพ.233', 'CS222 or CS233', 'Seminar on current research and development in operating systems.', 'หัวข้อเลือกสรรจากความก้าวหน้าด้านงานวิจัยและเทคโนโลยีของระบบปฏิบัติการ ที่เปลี่ยนแปลงตามยุคสมัยและเทคโนโลย'),
('', 'CS340', 'คพ.340', 'Selected Topics in Information Systems', 'หัวข้อเลือกสรรด้านระบบสารสนเทศ', 3, '(3-0-6)', '', 'คพ.251 หรือ คพ.356', 'CS251 or CS356', 'Seminar on current research and development in information systems.', 'หัวข้อเลือกสรรจากความก้าวหน้าด้านงานวิจัยและเทคโนโลยีของระบบสารสนเทศ ที่เปลี่ยนแปลงตามยุคสมัยและเทคโนโลยี'),
('', 'CS345', 'คพ.345', 'Practical Machine Learning and Data Mining', 'การเรียนรู้ของเครื่องจักรและการทำเหมืองข้อมูลเชิงประยุกต์', 3, '(3-0-6)', '', 'คพ.245', 'CS245', 'Fundamentals of algorithm design and data analysis associated with machine learning. Topics include techniques of statistical, probability theory, and combinatorial optimization. Concepts and techniques related to data mining; strengths and limitations of various data mining techniques, including classification, association analysis, and cluster analysis. ', 'หลักการพื้นฐานของการออกแบบอัลกอริทึมและการวิเคราะห์ข้อมูลส าหรับการเรียนรู้ของเครื่องจักร โดยใช้เทคนิคเชิงสถิติและความน่าจะเป็น การหาค่าเหมาะสมที่สุดเชิงการจัด สำหรับการเรียนรู้เชิงเครื่องจักร หลักการและเทคนิคในการทำเหมืองข้อมูลได้แก่ การจำแนกประเภท การวิเคราะห์ความสัมพันธ์และการจัดกลุ่ม รวมทั้งข้อดีและข้อจำกัดของเทคนิคดังกล่าว'),
('', 'CS346', 'คพ.346', 'Big Data Applications and Analytics', 'แอพพลิเคชันและการวิเคราะห์ข้อมูลขนาดใหญ่', 3, '(3-0-6)', '', '( คพ.451 หรือ คพ.251 ) และ คพ.345', '( CS451 or CS251 ) and CS345', 'Explore new technologies in modern database management systems. Discuss topics related to managing and using large-scale data sets in both high-performance transaction processing systems and large-scale analytical systems. All class projects will be in the context of real-world application domains, such as Internet advertising, health care, and social network analysis.', 'ศึกษาเทคโนโลยีที่ทันสมัยในระบบจัดการฐานข้อมูลสมัยใหม่ การจัดการและการทำงานกับชุดข้อมูลที่มีปริมาณมากในระบบประมวลข้อมูลประสิทธิภาพสูงและระบบการวิเคราะห์ข้อมูลขนาดใหญ่ การทำโครงงานที่เกี่ยวข้องกับข้อมูลขนาดใหญ่ที่มีอยู่จริง เช่น ข้อมูลโฆษณาทางอินเทอร์เน็ต ข้อมูลสุขภาพ และข้อมูลจากเครือข่ายสังคมออนไลน์'),
('', 'CS347', 'คพ.347', 'Data Warehousing and Business Intelligence', 'คลังข้อมูลและอัจฉริยะทางธุรกิจ', 3, '(3-0-6)', '', 'คพ.245', 'CS245', 'Data warehousing, data warehouse architecture, physical database design, dimension modeling; extraction, transformation, and loading, its applications to business intelligence, business analytics, OLAP, introduction to data mining, data visualization, data warehouse storage models and technology, business analytics techniques and tools for business intelligence', 'หลักการของคลังข้อมูล สถาปัตยกรรมระบบคลังข้อมูล การออกแบบฐานข้อมูลเชิงกายภาพตัวแบบเชิงมิติ การสกัด การแปลง และการโหลดข้อมูล การประยุกต์ใช้คลังข้อมูล การวิเคราะห์เชิงธุรกิจ การประมวลผลเชิงวิเคราะห์แบบออนไลน์ (OLAP) การทำเหมืองข้อมูลเบื้องต้น และการทำมโนภาพข้อมูล (Visualization) ตัวแบบและเทคโนโลยีการจัดเก็บข้อมูล เครื่องมือ และเทคนิคโปรแกรมส าเร็จรูป เพื่อสร้างอัจฉริยะทางธุรกิจ'),
('', 'CS348', 'คพ.348', 'Modeling for Data Science', 'แบบจำลองสำหรับวิทยาการข้อมูล', 3, '(3-0-6)', '', 'คพ.245', 'CS245', 'Fundamentals of statistical inference and testing, and introduction to statistical modeling. Inference and testing, covering topics such as maximum likelihood estimates, hypothesis testing, likelihood ratio test, Bayesian inference. Introduction to statistical modeling via introductory lectures on linear regression models, generalized linear regression models, nonparametric regression, and statistical computing. Application of statistical models as a means of representing and manipulating data, modeling uncertainty, and discovering new insights from data.', 'หลักการพื้นฐานสำหรับการอนุมานเชิงสถิติและการทดสอบ ได้แก่ วิธีภาวะน่าจะเป็นสูงสุด การทดสอบสมมุติฐาน การทดสอบ likelihood ratio การอนุมานแบบเบย์ เป็นต้น หลักการพื้นฐานของแบบจำลองเชิงสถิติ ได้แก่ โมเดลการถดถอยเชิงเส้น การถดถอยแบบไร้พารามิเตอร์ การคำนวณเชิงสถิติเป็นต้น การนำแบบจ าลองเชิงสถิติไปใช้สำหรับการแทนข้อมูล การจัดด าเนินการข้อมูล การจำลองความไม่แน่นอน และการค้นหาความเข้าใจในเชิงลึกจากข้อมูลที่มี\r\n'),
('', 'CS350', 'คพ.350', 'Selected Topics in Programming Languages', 'หัวข้อเลือกสรรด้านภาษาโปรแกรม', 3, '(3-0-6)', '', 'คพ.241', 'CS241', 'Seminar on current research and development in programming languages.', 'หัวข้อเลือกสรรจาก ความก้าวหน้าด้านงานวิจัยและเทคโนโลยีของภาษาโปรแกรมที่น่าสนใจ ที่เปลี่ยนแปลงตามยุคสมัยและเทคโนโลยี'),
('', 'CS351', 'คพ.351', 'Business Computing and Electronic Commerce', 'ระบบคอมพิวเตอร์ในธุรกิจและการพาณิชย์อิเล็กทรอนิกส', 3, '(3-0-6)', '', 'คพ.251', 'CS251', 'Concepts of information systems in business management, business application software, business processes over computer networks, electronic commerce infrastructures, computing and data exchange standards.', 'แนวคิดการใช้งานระบบสารสนเทศในการบริหารจัดการธุรกิจ โปรแกรมคอมพิวเตอร์ประยุกต์ในงานธุรกิจ การด าเนินกิจกรรมทางธุรกิจผ่านเครือข่ายคอมพิวเตอร์ โครงสร้างพื้นฐานของพาณิชย์อิเล็กทรอนิกส์ มาตรฐานการด าเนินการและการแลกเปลี่ยนข้อมูลทางอิเล็กทรอนิกส'),
('', 'CS352', 'คพ.352', 'Data-Driven Decision Making for Business', 'กระบวนการตัดสินใจทางธุรกิจโดยอิงพื้นฐานจากข้อมูล', 3, '(3-0-6)', '', 'คพ.251', 'CS251', 'Basic concepts of data management, theoretical and technological knowledge about business analytics with the emphasis on having a critical thinking process to frame a business question as a data question, identify and acquire data and other necessary resources, manage the development of solutions systematically, apply data or simulation modeling as needed, evaluate of the results and utilize them as the basis for making informed, evidence-based decisions, and business case studies', 'แนวคิดพื้นฐานในการบริหารจัดการข้อมูล ทฤษฎีและเทคโนโลยีที่เกี่ยวข้องในการวิเคราะห์ ข้อมูลเชิงธุรกิจ เน้นกระบวนการคิดเชิงวิพากษ์เพื่อการวางกรอบปัญหาทางธุรกิจเป็นปัญหาเชิงข้อมูล การระบุและได้มาซึ่งชุดข้อมูลและทรัพยากรอื่นๆ ที่ต้องใช้ในการแก้ปัญหา การบริหารจัดการปัญหา อย่างเป็นระบบ การแก้ปัญหาโดยอาศัยแบบจำลองข้อมูลหรือแบบจำลองสถานการณ์อย่างเหมาะสม การประเมินผลลัพธ์และประยุกต์ใช้ผลนั้นเพื่อสนับสนุนการตัดสินใจบนพื้นฐานของข้อมูล และกรณีศึกษาในธุรกิจ'),
('', 'CS353', 'คพ.353', 'Information Retrieval', 'การค้นคืนสารสนเทศ', 3, '(3-0-6)', '', 'คพ.251', 'CS251', 'Theories and techniques on computerized information indexing and retrieval. Topics include Boolean model, vector model, text processing and analysis, evaluation of information retrieval systems, Web-based search engines.', 'ทฤษฎีและกระบวนการสร้างดรรชนีและการค้นคืนสารสนเทศด้วยระบบคอมพิวเตอร์ ตัวแบบแบบบูล ตัวแบบแบบเวกเตอร์ การประมวลผลและวิเคราะห์ข้อความ การประเมินระบบค้นคืนสารสนเทศโปรแกรมค้นหาบนเว็บ'),
('', 'CS354', 'คพ.354', 'Database Systems 2', 'ระบบฐานข้อมูล 2', 3, '(3-0-6)', '', 'คพ.251', 'CS251', 'Advanced database management system design principles and techniques. Topics may be selected from: access methods, query processing and optimization, transaction management: concurrency control, recovery, and data security; distributed database systems: concepts, design and transaction management, and introduction to objectoriented database systems.', 'หลักการและเทคนิคการออกแบบระบบการจัดการฐานข้อมูลขั้นสูง เนื้อหาครอบคลุม วิธีเข้าถึงประสิทธิภาพและการประมวลผลข้อค าถาม การประมวลผลรายการเปลี่ยนแปลง การควบคุมภาวะพร้อมกัน การกู้ข้อมูล และความปลอดภัยของข้อมูล ระบบฐานข้อมูลแบบกระจาย แนวคิด การออกแบบและการจัดการรายการเปลี่ยนแปลง แนะน าระบบฐานข้อมูลเชิงวัตถุ'),
('', 'CS355 ', 'คพ.355', 'Compiler Construction', 'การสร้างโปรแกรมแปลภาษา', 3, '(3-0-6)', '', 'คพ.314', 'CS314', 'Basic concepts of compiler design and implementation lexical analysis, syntax and\r\nsemantic analysis, symbol table and object code generation and code optimization, error recovery and runtime memory management.', 'การพัฒนาโปรแกรมแปลภาษา การวิเคราะห์เล็กซิคอล การวิเคราะห์ไวยกรณ์และความหมายของภาษาโปรแกรม การสร้างตารางสัญลักษณ์ การสร้างรหัส การคืนสภาพเมื่อเกิดข้อผิดพลาด ตลอดจนการจัดการหน่วยความจำและการสนับสนุนขณะทำงาน'),
('', 'CS356', 'คพ.356', 'Management Information Systems', 'ระบบสารสนเทศเพื่อการบริหาร', 3, '(3-0-6)', '', 'คพ.251', 'CS251', 'Fundamental of information systems, organizations and management; Information technology infrastructure; Key System Applications: management and enterprise information systems; Building information systems; Managing information systems; Ethics and social impact of information systems\r\n', 'แนวคิดเบื้องต้นเกี่ยวกับระบบสารสนเทศ องค์กร และการบริหาร โครงสร้างพื้นฐานทางด้านเทคโนโลยีสารสนเทศสำหรับองค์กร ระบบสารสนเทศที่ส าคัญในองค์กร อาทิ ระบบสารสนเทศเพื่อการบริหาร ระบบสารสนเทศเพื่อการดำเนินงาน แนวทางการพัฒนาระบบสารสนเทศและการบริหารการใช้งานระบบ ประเด็นทางด้านจริยธรรมและผลกระทบทางด้านสังคมที่เกี่ยวข้องกับการใช้ระบบ'),
('', 'CS357', 'คพ.357', 'Information Systems for Entrepreneur Management', 'ระบบสารสนเทศเพื่อการบริหารธุรกิจผู้ประกอบการ', 3, '(3-0-6)', '', 'พบ.291 และ คพ.351', 'BA291 and CS351', 'Entrepreneurial setting of informatics company, introduction to financial management, marketing, opportunity assessment, intellectual property rights, management of ICT-based product, team formation, negotiations, creativity skills and business plan development for informatics business, ethics and awareness of an entrepreneur, case studies.', 'โครงสร้างของสารสนเทศ หลักการและกระบวนการในการเป็นผู้ประกอบการดำเนินธุรกิจทางด้านสารสนเทศ ความรู้เบื้องต้นในการบริหารการเงิน การตลาด การประเมินโอกาส การคุ้มครองทรัพย์สินทางปัญญา การจัดการสินค้าและบริการด้านเทคโนโลยีสารสนเทศ การสร้างทีมงาน การทำข้อตกลงทางธุรกิจ ความคิดสร้างสรรค์และการสร้างแผนธุรกิจ จรรยาบรรณและสำนึกการเป็นผู้ประกอบการ และกรณีศึกษา'),
('', 'CS360', 'คพ.360', 'Selected Topics in Software Engineering', 'หัวข้อเลือกสรรด้านวิศวกรรมซอฟต์แวร์', 3, '(3-0-6)', '', 'คพ.264', 'CS264', 'Seminar on current research and development in software engineering.', 'หัวข้อเลือกสรรจากความก้าวหน้าด้านงานวิจัยและเทคโนโลยีของวิศวกรรมซอฟต์แวร์ ที่เปลี่ยนแปลงตามยุคสมัยและเทคโนโลยี\r\n'),
('', 'CS361', 'คพ.361', 'Mobile Application Development', 'การพัฒนาโปรแกรมประยุกต์สำหรับอุปกรณ์พกพา', 3, '(3-0-6)', '', 'คพ.251', 'CS251', 'Developing landscape of mobile applications, web-based mobile applications, mobile platforms, the specific constraints and requirements of user interface design for limited-resource devices, conceptual overview, design issues, and practical development issues.', 'ภาพรวมการพัฒนาโปรแกรมประยุกต์ส าหรับอุปกรณ์พกพา เว็บแอพพลิเคชันบนอุปกรณ์พกพาแพลตฟอร์มของอุปกรณ์พกพา ข้อจ ากัดและความต้องการในการออกแบบส่วนต่อประสานผู้ใช้สำหรับ\r\nอุปกรณ์ที่มีทรัพยากรจ ากัด แนวคิดโดยรวม ปัญหาการออกแบบ และขั้นตอนการพัฒนาในทางปฏิบัต'),
('', 'CS364', 'คพ.364', 'Application Programming Interface', 'การใช้งานส่วนต่อประสานโปรแกรมประยุกต์', 3, '(3-0-6)', '', 'คพ.264', 'CS264', 'Workshop in using Application Programming Interface, user interface programming including streams and files, data collection library, and event-driven programming.', 'ฝึกปฏิบัติในการโปรแกรมโดยอาศัยส่วนต่อประสานโปรแกรมประยุกต์ การโปรแกรมส่วนต่อประสานผู้ใช้ รวมถึงสตรีมและแฟ้มข้อมูล ไลบรารี่สำหรับจัดการข้อมูล และการโปรแกรมเชิงเหตุการณ์');
INSERT INTO `courses-61` (`courseGrorp`, `courseID_EN`, `courseID_TH`, `courseName_EN`, `courseName_TH`, `courseUnit`, `courseHour`, `notCount`, `mustTaken`, `mustTaken_EN`, `courseDescrip_EN`, `courseDescrip_TH`) VALUES
('', 'CS366', 'คพ.366', 'Enterprise Software Architecture', 'สถาปัตยกรรมซอฟต์แวร์วิสาหกิจ', 3, '(3-0-6)', '', 'คพ.266', 'CS266', 'Concepts of enterprise software architecture; enterprise software architectural styles from both the structural and behavioral viewpoints together with strengths and weaknesses of each; study architectural design patterns and how to apply these patterns, case studies of techniques towards how to design enterprise software architecture.', 'แนวคิดเกี่ยวกับสถาปัตยกรรมซอฟต์แวร์วิสาหกิจ สถาปัตยกรรมซอฟต์แวร์วิสาหกิจจากมุมมองด้านโครงสร้างและพฤติกรรมการท างานของระบบ รวมทั้งจุดแข็งและจุดอ่อนของแต่ละด้านการศึกษาแม่แบบสถาปัตยกรรมซอฟต์แวร์วิสาหกิจ และการประยุกต์ใช้แม่แบบสถาปัตยกรรมและกรณีศึกษาการใช้เทคนิคในการออกแบบสถาปัตยกรรมซอฟต์แวร์วิสาหกิจ'),
('', 'CS367', 'คพ.367', 'Web Service Development Concepts', 'แนวคิดการพัฒนาเว็บบริการ', 3, '(3-0-6)', '', '- คพ.251 และ คพ.234\r\nหรือ\r\n- คพ.251 และ คพ.322\r\nแบบใดแบบหนึ่ง', '- CS251 and CS234\r\nหรือ\r\n- CS251 and CS322\r\nOne of the above.', 'Basic concepts of web services, web service architecture and related standards, security issues and protocols for web services, industrial technologies relating to web service developments, applying theoretical concepts in designing and developing web services for businesses.', 'แนวคิดและทฤษฎีเกี่ยวกับเว็บบริการ สถาปัตยกรรมเว็บบริการ มาตรฐานที่เกี่ยวข้องทางเว็บบริการ โปรโตคอลการรักษาความปลอดภัยของเว็บบริการ เทคโนโลยีที่ใช้ในการพัฒนาเว็บบริการ การบูรณาการทฤษฎีกับการออกแบบพัฒนาเว็บบริการเพื่อใช้งานจริงในทางธุรกิจ'),
('', 'CS368', 'คพ.368', 'Entrepreneurship for Digital Product', 'การเป็นผู้ประกอบการสำหรับผลิตภัณฑ์ดิจิทัล', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Study of the entrepreneurial process focusing on the digital product development and management; ideation, innovation, startup models. Practice entrepreneurial activities: product vision creation, business case analysis, opportunities analysis, market position identification, digital product design and development.', 'กระบวนการของผู้ประกอบการโดยเน้นที่การพัฒนาและบริหารผลิตภัณฑ์ดิจิทัลการสร้างแนวคิด ความคิดสร้างสรรค์ รูปแบบของการท าธุรกิจเริ่มต้น ฝึกปฏิบัติกิจกรรมของผู้ประกอบการการสร้างวิสัยทัศน์ของสินค้า การวิเคราะห์กรณีธุรกิจ การวิเคราะห์โอกาสของผลิตภัณฑ์การระบุตำแหน่งในตลาดของผลิตภัณฑ์ การออกแบบและพัฒนาผลิตภัณฑ์'),
('', 'CS369', 'คพ.369', 'Web Application Development', 'การพัฒนาเว็บแอพพลิเคชัน', 3, '(2-2-4)', '', 'คพ.234 หรือ คพ.322', 'CS234 or CS322', 'Basic systems and protocols for providing services on the internet, developing and deploying web applications, topics covered web application development techniques for both client side and server side, session management, interfacing with other online services, web application security, web design patterns and reusable web application components.', 'พื้นฐานระบบและโพรโทคอลการให้บริการทางอินเทอร์เน็ต การพัฒนาและการติดตั้งเว็บแอพพลิเคชัน โดยหัวข้อครอบคลุมเทคนิคการพัฒนาเว็บแอพพลิเคชันทั้งด้านเว็บไคลแอนต์ และเซิร์ฟเวอร์การจัดการเซสชัน การทำงานร่วมกับระบบบริการออนไลน์อื่น การรักษาความมั่นคง แพทเทิร์นการออกแบบเว็บ และการนำองค์ประกอบของเว็บแอพพลิเคชันกลับมาใช้อีก'),
('', 'CS370', 'คพ.370', 'Selected Topics in Artificial Intelligent Systems', 'หัวข้อเลือกสรรด้านระบบปัญญาประดิษฐ์', 3, '(3-0-6)', '', 'คพ.265', 'CS265', 'Seminar on current research and development in artificial intelligent systems.', 'หัวข้อเลือกสรรจากความก้าวหน้าด้านงานวิจัยและเทคโนโลยีทางด้านปัญญาประดิษฐ์ ที่เปลี่ยนแปลงตามยุคสมัยและเทคโนโลย'),
('', 'CS373', 'คพ.373', 'Seminar in Software Engineering', 'สัมมนาด้านวิศวกรรมซอฟต์แวร์', 3, '(3-0-6)', '', 'คพ.264', 'CS264', 'Seminar and field trip to study industrial use of best practices and standards of Software Engineering. ', 'สัมมนาและดูงานหัวข้อต่าง ๆ ที่น่าสนใจ และเป็นประโยชน์เพื่อแสดงให้เห็นแนวทางการประยุกต์ใช้และแนวทางปฏิบัติที่ดีรวมถึงมาตรฐานของ วิศวกรรมซอฟต์แวร์ในภาคอุตสาหกรรม'),
('', 'CS374', 'คพ.374', 'Formal Methods', 'วิธีรูปนัย', 3, '(3-0-6)', '', 'คพ.314', 'CS314', 'Introduction to different mathematical models and languages, known as formal methods used to model software and verify its correctness.', 'พื้นฐานทางคณิตศาสตร์และตรรกศาสตร์จากภาษารูปนัย เพื่อสร้างโมเดลในการพัฒนาซอฟต์แวร์ที่มีความถูกต้อง\r\n'),
('', 'CS375', 'คพ.375', 'Software Project Management', 'การจัดการโครงการซอฟต์แวร์', 3, '(3-0-6)', '', 'คพ.266 และ คพ.267', 'CS266 and CS267', 'Introduce knowledge in managing and controlling software project, project proposal development techniques including business case analysis, software cost and schedule estimation, project planning, risk management, resource management, software project control and software project evaluations.', 'แนะนำองค์ความรู้ในการจัดการและควบคุมโครงการซอฟต์แวร์ เทคนิคการเขียนข้อเสนอโครงการการวิเคาระห์ผลทางธุรกิจของการทำโครงการซอฟต์แวร์ การวิเคราะห์ประมาณราคาและระยะเวลาการวางแผน การจัดการความเสี่ยง การจัดสรรทรัพยากร การติดตามควบคุมโครงการ การประเมินผลสำเร็จของโครงการซอฟต์แวร์'),
('', 'CS376', 'คพ.376', 'Artificial Intelligence in Practice', 'ปัญญาประดิษฐ์กับการประยุกต์', 3, '(3-0-6)', '', 'คพ.265', 'CS265', 'Probabilistic reasoning, non-monotonic reasoning, frame, conceptual graph, Bayesian networks, markov networks, relational probability models, hidden Markov models, decision theory. This course focuses on implementation using artificial intelligence programming such as prolog, lisp or python.', 'การให้เหตุผลเชิงสถิติ การให้เหตุผลแบบนอนโมโนโทนิก การแสดงความรู้แบบเฟรม การแสดงความรู้แบบกราฟมโนภาพ โครงข่ายแบบเบย์ โครงข่ายแบบมาร์คอฟ แบบจ าลองความน่าจะเป็นเชิงสัมพันธ์ แบบจ าลองฮิดเดนมาร์คอฟ และ ทฤษฎีการตัดสินใจ โดยเน้นการพัฒนาระบบด้วยภาษาโปรแกรมทางด้านปัญญาประดิษฐ์ เช่น โปรล็อก ลิตพ์ และ ไพธอน'),
('', 'CS377', 'คพ.377', 'Machine Learning', 'การเรียนรู้ของเครื่องจักร', 3, '(3-0-6)', '', 'คพ.265', 'CS265', 'Learning theory, inductive and deductive learning, naïve Bayesian learning, decision trees, supervised learning, unsupervised learning, reinforcement learning, overfitting problem, measuring learning accuracy, and applications of machine learning, such as data mining, robotic control, autonomous navigation, and bioinformatics.', 'ทฤษฎีการเรียนรู้การเรียนรู้เชิงอุปนัยและนิรนัย การเรียนรู้เบย์อย่างง่าย ต้นไม้ตัดสินใจ การเรียนรู้แบบมีผู้สอน การเรียนรู้แบบไม่มีผู้สอน การเรียนรู้แบบเสริมแรง ปัญหาการเข้ากันมากเกินไป การประเมินความถูกต้องของการเรียนรู้และ ตัวอย่างการประยุกต์ใช้การเรียนรู้ของเครื่อง เช่น การทำเหมืองข้อมูล การควบคุมหุ่นยนต์การนำทางแบบอัตโนมัติ และ ชีวสารสนเทศศาสตร์'),
('', 'CS378', 'คพ.378', 'Advanced Search Strategies', 'กลยุทธ์การค้นหาขั้นสูง', 3, '(3-0-6)', '', 'คพ.265', 'CS265', 'Search space, combinatorial search, heuristic search, stochastic search, search tree, simulated annealing algorithm, evolutionary algorithm, local optimum problem, ridge and plateau problem, Performance evaluation, and example of applications.', 'ปริภูมิค้นหา การค้นหาเชิงการจัด การค้นหาแบบฮิวริสติก การค้นหาแบบสุ่ม ต้นไม้ค้นหา ขั้นตอนวิธีการจ าลองการอบ ขั้นตอนวิธีเชิงวิวัฒน์ ปัญหาโลคอลออฟติมัม ปัญหาการลู่เข้าสู่เป้าหมายได้ช้า การประเมินประสิทธิภาพของค าตอบ และตัวอย่างของการประยุกต์ใช้'),
('', 'CS379', 'คพ.379', 'Natural Language Processing', 'การประมวลภาษาธรรมชาติ', 3, '(3-0-6)', '', 'คพ.265', 'CS265', 'Deterministic and stochastic grammars, morphological analysis, syntax analysis, semantic analysis, discourse analysis, and applications (e.g. machine translation, speech recognition and synthesis, and text mining)', 'ไวยากรณ์เชิงก าหนดและไวยากรณ์แบบอิงสถิติการวิเคราะห์วจีวิภาค การวิเคราะห์วากยสัมพันธ์ การวิเคราะห์อรรถศาสตร์ การวิเคราะห์สัมพันธสาร และการประยุกต์ใช้ต่างๆ ได้แก่ การแปลภาษาด้วยคอมพิวเตอร์ การรู้จ าและการสังเคราะห์เสียง และ การท าเหมืองข้อมูลข้อความ'),
('', 'CS381', 'คพ.381 ', 'Digital Image Processing', 'การประมวลภาพดิจิทัล', 3, '(3-0-6)', '', 'คพ.213', 'CS213', 'Digital image fundamentals, color models, image transform, image enhancement, spatial-domain and frequency-domain filters, image segmentation, binary morphology, image representation and description, applications of digital image processing.', 'ความรู้พื้นฐานเกี่ยวกับภาพดิจิทัล การแทนค่าข้อมูลสี การแปลงข้อมูลภาพ การปรับปรุงคุณภาพของภาพ ตัวกรองในโดเมนพื้นที่และโดเมนความถี่ การแบ่งภาพเป็นหลายส่วนอย่างมีความหมาย ไบนารี มอร์โฟโลยี การแทนค่าและการบรรยายลักษณะข้อมูลภาพ การประยุกต์ใช้ข้อมูลภาพดิจิทัล'),
('', 'CS382', 'คพ.382', 'Introduction to Computer Vision', 'ทัศนศาสตร์คอมพิวเตอร์เบื้องต้น', 3, '(3-0-6)', '', 'คพ.381', 'CS381', 'Image acquisition, image preprocessing, object detection, feature extraction, object recognition, motion analysis, applications for computer vision', 'การได้มาซึ่งภาพดิจิทัล การประมวลผลก่อน การตรวจหาวัตถุในภาพ การหาคุณลักษณะวัตถุ การรู้จำวัตถุ การวิเคราะห์การเคลื่อนไหว การประยุกต์ใช้ทัศนศาสตร์คอมพิวเตอร์'),
('', 'CS384', 'คพ.384', 'Human – Computer Interaction', 'การปฏิสัมพันธ์ระหว่างมนุษย์และคอมพิวเตอร์', 3, '(3-0-6)', '', 'คพ.264', 'CS264', 'Importance of human-computer interaction (HCI) to the development of acceptable and usable systems, context for HCI, user-centered design, evaluation, measure of usability, human-information processing model applicable to HCI, most common interface design mistakes, and user interface principle and guildines', 'ตระหนักถึงความส าคัญการศึกษาปฏิสัมพันธ์ระหว่างคอมพิวเตอร์และมนุษย์มีผลต่อการพัฒนาระบบคอมพิวเตอร์ให้ยอมรับได้และมีความสามารถใช้งานได้ ศึกษาบริบทที่ส าคัญต่อการปฏิสัมพันธ์ระหว่างคอมพิวเตอร์และมนุษย์ กระบวนการพัฒนาระบบแบบผู้ใช้เป็นศูนย์กลาง การประเมินและมาตรวัดความสามารถใช้งานได้ ปัจจัยทางมนุษย์ที่เกี่ยวข้องกับการประมวลผลสารสนเทศของมนุษย์ และกฏเกณฑ์และหลักการที่ใช้ตลอดจน ข้อผิดพลาดที่เกิดขึ้นบ่อย ๆ ในการออกแบบส่วนต่อประสาน'),
('', 'CS385', 'คพ.385', 'Human-Centered Data Science', 'วิทยาการข้อมูลที่มีมนุษย์เป็นศูนย์กลาง', 3, '(3-0-6)', '', 'คพ.245', 'CS245', 'Human aspects of data science, data ethics and data privacy, legal frameworks and intellectual property, provenance and reproducibility, data curation and preservation, user experience design and usability testing, data communication and societal impacts of\r\ndata science.', 'วิทยาการข้อมูลเชิงบุคคล วิทยาการข้อมูลเชิงมนุษย์วิทยาการข้อมูลในแง่มุมที่เกี่ยวข้องกับมนุษย์ จริยธรรมและความเป็นส่วนตัวของข้อมูล กรอบความคิดเกี่ยวกับกฎหมายและลิขสิทธิทางปัญญา ต้นแบบและการผลิตซ้ า การเก็บรักษาข้อมูล การออกแบบ UX และการทดสอบความใช้งานได้ การสื่อสารข้อมูล และอิทธิพลของวิทยาการข้อมูลต่อสังคม'),
('', 'CS386', 'คพ.386', 'Instructional Design and Development of Interactive Multimedia', 'การออกแบบและพัฒนาบทเรียนมัลติมีเดียเชิงปฏิสัมพันธ์', 3, '(3-0-6)', '', 'คพ.312', 'CS312', 'Principles of and research in interactive multimedia, design, develop and evaluate a prototype of interactive multimedia instructional system', 'ทฤษฎีที่เกี่ยวข้องการออกแบบบทเรียนมัลติมีเดียเชิงปฏิสัมพันธ์ และงานวิจัย ออกแบบ พัฒนาและประเมินผลบทเรียนมัลติมีเดียเชิงปฏิสัมพันธ์\r\n'),
('', 'CS389', 'คพ.389', 'Selected Topics in Human-Computer Interaction', 'หัวข้อเลือกสรรด้านการปฏิสัมพันธ์ระหว่างมนุษย์และคอมพิวเตอร์', 3, '(3-0-6)', '', 'คพ.384', 'CS384', 'Seminar on current research and development in human-computer interaction', 'หัวข้อเลือกสรรจากความก้าวหน้างานวิจัยและเทคโนโลยีด้านการปฏิสัมพันธ์ระหว่างมนุษย์และคอมพิวเตอร์'),
('', 'CS390', 'คพ.390', 'Selected Topics in Multimedia Content Analysis', 'หัวข้อเลือกสรรด้านการวิเคราะห์ข้อมูลมัลติมีเดีย', 3, '(3-0-6)', '', 'คพ.381', 'CS381', 'Selected Topic on current research and development in multimedia content analysis', 'หัวข้อเลือกสรรจากความก้าวหน้างานวิจัยและเทคโนโลยีด้านการวิเคราะห์ข้อมูลมัลติมีเดียที่เปลี่ยนแปลงตามเทคโนโลย'),
('', 'CS396', 'คพ.396', 'Computer Graphics Modeling', 'การจำลองด้านคอมพิวเตอร์กราฟิก', 3, '(3-0-6)', '', 'คพ.111 หรือ คพ.112', 'CS111 or CS112', '3D Modeling:polygon, parametric primitives, NURBS, lathed and extruded objects, subdivision surfaces, level of detail; character design: physical attributes and designing for animation; architectural design.', 'การสร้างรูปทรงทางเรขาคณิตของวัตถุ 3 มิติ โดยการใช้รูปหลายเหลี่ยม สมการพาราเมทริกซ์ การใช้เนิร์บ การสร้างโครงและสร้างผิวตามโครง การสร้างผิวหน้าแบบแบ่งย่อย การสร้างรูปทรงที่มีความละเอียดของข้อมูลต่างกัน การออกแบบตัวแสดง การกำหนดคุณลักษณะของร่างกายและการออกแบบตัวแสดงที่เหมาะสมส าหรับการสร้างภาพเคลื่อนไหว การออกแบบรูปทรงสำหรับใช้ในงานด้านสถาปัตยกรรม'),
('', 'CS397', 'คพ.397', 'Computer Graphics 2', 'คอมพิวเตอร์กราฟิก 2', 3, '(3-0-6)', '', 'คพ.299', 'CS299', 'Curves and surfaces; Visible Surface Determination; The rendering equation; spectral colour; realism and visual perception; visibility: scanline, zbuffer, ray-tracing; local lighting; shading models; texturing and texture synthesis; bump mapping; the basics of anti-aliasing', 'การสร้างเส้นโค้งและพื้นผิวการลบพื้นผิวแฝงสมการที่ใช้ในการคำนวณแสงและเงาสีของลำแสงสีจริงและการมองเห็น วิธีการสร้างภาพให้มองเห็นได้ ตามแนวเส้นตรงในแนวนอน การใช้ซีบัฟเฟอร์การติดตามแนวรังสีของแสงแสงที่ค านวณแยกเฉพาะที่การแรเงาวัตถุลวดลายบนพื้นผิวและการสังเคราะห์ลวดลายบนพื้นผิวการทาลวดลายโดยวิธีการปรับแนวเส้นตั้งฉากการแก้ปัญหาการเกิด-แอเลียสขั้นต้น'),
('', 'CS399', 'คพ.399', 'Selected Topics in Computer Graphics', 'หัวข้อเลือกสรรด้านคอมพิวเตอร์กราฟิก', 3, '(3-0-6)', '', 'คพ.299', 'CS299', 'Seminar on current research and development in computer graphics.', 'หัวข้อเลือกสรรจากความก้าวหน้าด้านงานวิจัยและเทคโนโลยีของคอมพิวเตอร์กราฟิกที่เปลี่ยนแปลงตามยุคสมัยและเทคโนโลย'),
('', 'CS403', 'คพ.403', 'Special Projects 2', 'โครงงานพิเศษ 2', 6, '(0-18-0)', '', 'คพ.303 และสอบได้ไม่ต่ำกว่า C', 'CS303 with a minimum of C', 'Study the Projects proposed in CS 303 in details, implement the proposed idea, write papers and present results to the committee. ', 'ึศึกษาค้นคว้าโครงงานที่ได้เสนอในลักษณะวิชา คพ.303 ให้ลึกซึ้งกว้างขวางยิ่งขึ้น เขียนรายงาน และเสนอต่อคณะกรรมการ จัดพิมพ์เป็นรูปเล่ม'),
('', 'CS404', 'คพ.404', 'Co-operative Education 2', 'สหกิจศึกษา 2', 6, '(≧ 270 h.)', '', 'คพ.304', 'CS304', 'Supervised practical training on the given assignments from authorized body from the faculty. Student must show the capability in implementation of knowledge and skill in the actual working environmemt. Written report of design, development, and implementation must be submitted the end of practical period', 'การปฏิบัติงานที่ได้รับมอบหมายจากสถานประกอบการที่ได้รับความ เห็นชอบจากสาขาวิชา โดยนักศึกษาต้องน าความรู้ทางวิชาการที่ได้เรียนไปประยุกต์ใช้และฝึกทักษะในภาวะแวดล้อมการทำงานจริงภายใต้การกำกับดูแลของสถาน ประกอบการนั้น โดยต้องแสดงงานที่ได้รับมอบหมายอย่างชัดเจน พร้อมทั้งแนวคิดที่ ใช้ในการออกแบบ พัฒนาและประยุกต์ เมื่อเสร็จสิ้นโครงงานแล้วต้องจัดส่งผลงานในรูปแบบของรายงานตามที่สาขาวิชาก าหนด'),
('', 'CS434 ', 'คพ.434', 'Computer and Network Security', 'ความปลอดภัยของระบบคอมพิวเตอร์และเครือข่าย', 3, '(3-0-6)', '', 'คพ.334', 'CS334', 'Security of information, computer systems, databases, networks and communications, symmetric and asymmetric cryptography, digital signatures, digital certificates, malwares.', 'ความปลอดภัยของสารสนเทศ ระบบคอมพิวเตอร์ ฐานข้อมูล เครือข่ายและการสื่อสาร การเข้ารหัสแบบสมมาตรและอสมมาตร ลายมือชื่อดิจิทัล ใบรับรองดิจิทัล โปรแกรมที่มีจุดประสงค์ร้าย'),
('', 'CS435', 'คพ.435', 'Network Design and Management', 'การออกแบบและการจัดการเครือข่าย', 3, '(3-0-6)', '', 'คพ.322 หรือ คพ.334', 'CS322 or CS334', 'Topics in computer network design and management, case Studies. IP address subnetting, virtual local area networks (VLANs), congestion controls, resource allocations for providing quality of service (QoS), classic and state-of-the-art network management protocols, network performance analysis.', 'หัวข้อเกี่ยวกับการออกแบบเครือข่าย การจัดการเครือข่าย และตัวอย่างการประยุกต์ใช้การจัดแบ่งเลขที่ไอพี ข่ายงานบริเวณเฉพาะที่แบบเสมือน การควบคุมความคับคั่งของเครือข่าย การจัดสรรทรัพยากรเครือข่ายเพื่อสร้างให้เกิดคุณภาพของการให้บริการ โพรโทคอลสนับสนุนการจัดการเครือข่าย การเฝ้าระวังสมรรถนะของเครือข่าย\r\n'),
('', 'CS438', 'คพ.438', 'Internetworking and Distributed Systems Laboratory', 'ปฏิบัติการตั้งค่าระบบคอมพิวเตอร์แบบกระจาย', 3, '(3-0-6)', '', '- คพ.222 และ คพ.322 ทั้งสองวิชาสอบได้ไม่ต่ำกว่า C\r\nหรือ\r\n- คพ.334 สอบได้ไม่ต่ำกว', '- CS222 and CS322 in both with a minimum of C\r\nor\r\n- CS334 with a minimum of C+', 'Laboratory exercises in setting up distributed systems, operating systems, networked file Systems, important components based on the Internet standard: TCP/IP, DNS, and gateway, network management protocol: SNMP.', 'ทักษะที่เกี่ยวข้องกับการติดตั้งระบบคอมพิวเตอร์แบบกระจาย การตั้งค่าระบบปฏิบัติการ การตั้งค่าระบบไฟล์สำหรับระบบแบบกระจาย การตั้งค่าองค์ประกอบสำคัญของเครือข่ายตามข้อกำหนดของระบบเครือข่ายอินเทอร์เน็ต ได้แก่ ทีซีพี/ไอพี ดีเอ็นเอส เกตเวย์ และการตั้งค่าโพรโทคอลมาตรฐานสำหรับบริหารจัดการเครือข่าย ได้แก่ เอสเอ็นเอ็มพี'),
('', 'CS450', 'คพ.450', 'Selected Topics in Data Science', 'หัวข้อเลือกสรรด้านวิทยาการข้อมูล', 3, '(3-0-6)', '', 'คพ.245', 'CS245', 'The purpose of Selected Topics in Data Science being a topics course is to respond to new researches and technologies in the rapidly evolving fields of Data Science.', 'หัวข้อเลือกสรรจากความก้าวหน้าด้านงานวิจัยและเทคโนโลยีของวิทยาการข้อมูลที่เปลี่ยนแปลงตามยุคสมัยและเทคโนโลยี'),
('', 'CS451', 'คพ.451', 'Storing and Retrieving Data', 'การจัดเก็บและค้นคืนข้อมูล', 3, '(3-0-6)', '', 'คพ.245', 'CS245', 'Introduction to fundamentals of data storage, retrieval, and processing systems in the context of common data analytics processing needs. Concepts in big-data architectures. Structured and unstructured data. The preparation and management of datasets for analysis.', 'ระบบการจัดเก็บ การค้นคืนและการประมวลผลข้อมูล สำหรับการวิเคราะห์ข้อมูลพื้นฐาน สถาปัตยกรรมสำหรับการจัดเก็บและประมวลผลข้อมูลขนาดใหญ่ ประเภทข้อมูลแบบมีโครงสร้างและไม่มีโครงสร้าง การจัดเตรียมและการจัดการชุดข้อมูล ก่อนการวิเคราะห์'),
('', 'CS467 ', 'คพ.467', 'Software Configuration Management', 'การบริหารการจัดเก็บผลผลิตจากการพัฒนาซอฟต์แวร์', 3, '(3-0-6)', '', 'คพ.266', 'CS266', 'Knowledge and fundamental of control and maintenance software development for products integrity throughout project’s life cycles. Software configuration management process. Configuration baseline, and auditions.', 'องค์ความรู้และหลักการพื้นฐานของการจัดเก็บบำรุงรักษา และการควบคุมผลผลิต เพื่อความถูกต้องสมบูรณ์ของผลผลิตที่สร้างขึ้นในช่วงชีวิตของซอฟต์แวร์ ศึกษากระบวนการและการจัดการรวมถึงการนำเครื่องมือมาใช้เพื่อเพิ่มประสิทธิภาพของการจัดเก็บบำรุงรักษา และการควบคุมผลผลิต'),
('', 'EC210', 'ศ.210', 'Introductory Economics', 'เศรษฐศาสตร์เบื้องต้น', 3, '(3-0-6)', 'EE211 | EE212 | EE213 | EE214', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', '(For non-economics major only; credits will not be awarded to students who are taking or have completed EE211 or EE212 or EE213 or EE214)\r\nThe general principles of microeconomics and macroeconomics. In microeconomics part, topics cover demand for and supply of goods, consumer behavior, production and costs, structure and behavior of production units under perfectly and imperfectly competitive markets, the concept of market failures and the role of government intervention. In macroeconomics part, topics cover objectives and problems in macroeconomic, national income determination, money and banking system, introduction to fiscal and monetary policies used for economic stabilization, the application of economic indices to analyze the economic situation. In international economics part, topics cover importance of international trade and finance, and disputes between free trade and market protection.', '(เฉพาะนักศึกษานอกคณะเศรษฐศาสตร์เท่านั้น และจะไม่นับหน่วยกิตให้หากสอบได้วิชา ศ. 211 หรือศ. 212 หรือ ศ. 213 หรือ ศ. 214 ก่อนหรือหลัง หรือก าลังศึกษาวิชาเหล่านี้อยู่)\r\nหลักทั่วไปของเศรษฐศาสตร์จุลภาคและมหภาค ในส่วนของเศรษฐศาสตร์จุลภาค ศึกษาถึงอุปสงค์และอุปทานของสินค้า พฤติกรรมผู้บริโภค การผลิต และต้นทุน พฤติกรรมของหน่วยผลิต โครงสร้างและพฤติกรรมการแข่งขันของหน่วยผลิตในตลาดที่มีการแข่งขันอย่างสมบูรณ์ ตลาดผูกขาด และตลาดที่ไม่สมบูรณ์ แนวคิดความล้มเหลวของตลาด และบทบาทของภาครัฐในการแทรกแซงตลาด ในส่วนของเศรษฐศาสตร์มหภาค ศึกษาถึงเป้าหมาย และปัญหาในทางเศรษฐกิจมหภาค ความเข้าใจถึงรายได้ประชาชาติ ระบบการเงินและการธนาคาร นโยบายการเงินและการคลังในการรักษาสถียรภาพทางเศรษฐกิจ รวมทั้งการนำดัชนีชี้วัดเศรษฐกิจมหภาคไปใช้ในการวิเคราะห์สถานการณ์ทางเศรษฐกิจ ในภาคต่างประเทศศึกษาถึงความสำคัญของการค้าและการเงินระหว่างประเทศ และข้อโต้แย้งระหว่างการค้าเสรีและการปกป้องตลาด'),
('', 'EL295', 'สษ.295', 'Academic English I', 'ภาษาอังกฤษเชิงวิชาการ 1', 3, '(3-0-6)', '', 'สษ.172 หรือ มธ.105', 'EL172 or TU105', 'This course is designed to enhance English academic skills. Through the course, students are expected to be able to use learned vocabulary and phrases appropriately in speaking and writing, make good notes of audio features and written texts for revision, writing, and presentation. The course also aims to enhance students’s ability to write letters, e-mails and short essays with good organization and appropriate word selection, summarize short audio and written messages, make good questions and responses in discussion, interview, and surveys, plan and conduct a simple survey, and write survey report and present the results at acceptable level.', 'เพื่อพัฒนาทักษะภาษาอังกฤษด้านวิชาการ สามารถใช้ศัพท์ที่เรียนในการสื่อสารทั้งในการพูด และเขียน จดบันทึกข้อมูลส าคัญจากสิ่งที่ฟัง บันทึกร่างแผนการเขียนและการนำเสนอข้อมูล สามารถเขียนจดหมายและจดหมายอีเลคทรอนิค เรียงความขนาดสั้นที่มีองค์ประกอบสมบูรณ์ มีการเลือกใช้คำอย่างเหมาะสมกับผู้อ่านและวัตถุประสงค์ในการเขียน สามารถเขียนสรุปใจความของเรื่องที่ได้ฟังและอ่าน สามารถตั้งค าถามและตอบคำถามในการอภิปราย การสัมภาษณ์และการเก็บข้อมูลวิจัย รวมทั้งมีความสามารถวางแผนและทำการศึกษาประเด็นพื้นฐาน เขียนรายงานและนำเสนอผลการศึกษาได้'),
('', 'EL395', 'สษ.395', 'Academic English 2', 'ภาษาอังกฤษเชิงวิชาการ 2', 3, '(3-0-6)', '', 'สษ.295', 'EL295', 'To advance students’ English academic skills for more advanced level so that they will be able to comprehend and analyze long academic articles, summarize long written messages, rephrase and paraphrase academic paragraphs and selected academic articles. Students will also be trained to describe and write description of academic and survey graphics, credit source of information, plan and conduct a purposeful survey, write abstract and survey report, and clearly present the survey results.', 'เพื่อเพิ่มความสามารถและทักษะภาษาอังกฤษด้านวิชาการของผู้เรียนโดยการอ่านบทความขนาดยาวและเลือกประเด็นที่เกี่ยวข้องกับเรื่องที่สนใจ สามารถทำความเข้าใจและวิเคราะห์เรื่องที่อ่านสามารถเขียนสรุปและเขียนข้อมูลที่เลือกขึ้นใหม่โดยการเปลี่ยนคำและโครงสร้างภาษาในความหมายเดิม สามารถบรรยายและเขียนคำบรรยายภาพ แผนภูมิและกราฟแสดงข้อมูลจากการศึกษา และอ้างอิงแหล่งข้อมูลได้อย่างถูกต้อง สามารถท าโครงการศึกษาที่มีความซับซ้อนมากขึ้น และสามารถเขียนรายงานและนำเสนอผลการศึกษาได้'),
('', 'HR201', 'ทม.201', 'Modern Management and Entrepreneurship', 'การบริหารและการประกอบการสมัยใหม่', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Management and entrepreneurship concepts, evolution of management, roles and skills of managers, types and characteristics of entrepreneurs, planning, organizing, human resource management, leading, controlling, managerial decision making, ethics, and use of various management tools in the digital era', 'แนวคิดทางการบริหารและการประกอบการ วิวัฒนาการทฤษฎีการบริหาร หน้าที่และทักษะผู้บริหารองค์กร ประเภทและคุณลักษณะผู้ประกอบการ การวางแผน การจัดองค์การ การบริหารทรัพยากรมนุษย์ การเป็นผู้นำ การสร้างแรงจูงใจ และการควบคุม การตัดสินใจทางการบริหาร และจริยธรรม การบริหาร การใช้เครื่องมือทางการบริหารยุคดิจิตอล'),
('', 'MA211', 'ค.211', 'Calculus 1', 'แคลคูลัส 1', 3, '(3-0-6)', 'MA111 | MA216 | MA218 | AM101', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Limits and continuous functions, derivatives of algebraic and transcendental functions, the chain rule, implicit differentiation, higher-order derivatives, Rolle’s theorem, the mean-value theorem, applications of the derivative, indeterminate forms, L’Hospital’s rules and its application for finding the limits, differentials and applications, antiderivatives, indefinite integrals, formula of integration, integration by change variables, Riemann sum, definite integrals, the fundamental theorem of calculus,\r\nNote : There is no credit for students who are currently taking or have earned credits of MA111 or MA216 or MA218 or AM101', 'ลิมิตและความต่อเนื่องของฟังก์ชัน อนุพันธ์ของฟังก์ชันพีชคณิตและฟังก์ชันอดิศัย กฎลูกโซ่ อนุพันธ์โดยปริยาย อนุพันธ์อันดับสูง ทฤษฎีบทของรอล ทฤษฎีบทค่ามัชฌิม การประยุกต์ของอนุพันธ์ รูปแบบยังไม่กำาหนด หลักเกณฑ์โลปีตาลและการประยุกต์ในการหาลิมิต ผลต่างเชิงอนุพันธ์และการประยุกต์ ปฏิยานุพันธ์ ปริพันธ์ไม่จำกัดเขต สูตรการหาปริพันธ์ การหาปริพันธ์โดยการเปลี่นตัวแปรผลบวก รีมันน์ปริพันธ์จำกัดเขต ทฤษฎีบทหลักมูลของแคลคูลัส\r\nหมายเหตุ : ไม่นับหน่วยกิตให้ผู้ที่กำลังศึกษาหรือสอบได้ค.111 หรือ ค.216 หรือ ค.218 หรือ คป.101'),
('', 'PY252', 'จ.252', 'Psychology of Interpersonal Relations', 'จิตวิทยาความสัมพันธ์ระหว่างบุคคล', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Study of interpersonal relationship emphasizes overt behaviors of individuals in societies. The topics include psychological perspectives, understanding of self and others, individual differences, interpersonal perception, interpersonal attraction and other psychological principles to understand both positive and negative emotions in relations and to deal with interpersonal conflict in order to build appropriate relationships', 'ความสัมพันธ์ระหว่างบุคคลในสังคม เน้นพื้นฐานการแสดงออกของบุคคลในสังคมผ่านแนวคิดทางจิตวิทยา การเข้าใจตนเองและบุคคลอื่น การเข้าใจความแตกต่างระหว่างบุคคล การรับรู้ผู้อื่นแรงดึงดูดใจระหว่างบุคคล ตลอดจนการใช้หลักจิตวิทยาในการเข้าใจอารมณ์และความรู้สึกทั้งเชิงบวกและลบที่เกิดในความสัมพันธ์ และในการจัดการปัญหาที่เกิดขึ้นได้ เพื่อให้มีมนุษยสัมพันธ์ที่เหมาะสม'),
('', 'SC301', 'วท.301', 'Entrepreneurship in Science and Technology', 'การประกอบการด้านวิทยาศาสตร์และเทคโนโลยี', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Concepts of entrepreneurship, Structures of business plans, Starting up or Developing business, Feasibility study, basic knowledge on finance and investment, Marketing, Production, Human resource management, and Developing a business plan and field studies. ', 'แนวคิดการเป็นผู้ประกอบการ องค์ประกอบของแผนธุรกิจ วิธีการเริ่มธุรกิจหรือพัฒนาธุรกิจใหม่การศึกษาความเป็นไปได้ ความรู้เบื้องต้นเกี่ยวกับการเงินและการลงทุน การตลาด การผลิต การบริหารทรัพยากรมนุษย์ การจัดทำแผนธุรกิจ และมีการศึกษาดูงานนอกสถานที่'),
('', 'ST216', 'ส.216 ', 'Statistics for Social Science 1', 'สถิติสำหรับสังคมศาสตร์ 1', 3, '(3-0-6)', 'TU155', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'No credits for students who passed or studying TU155\r\nIntroduction to descriptive statistics; index numbers; unconditional and conditional probability; random variables and probability distribution; unconditional and conditional expectations; elementary sampling and sampling distribution; estimation and hypotheses testing for one and two population; statistical package results interpretation.', 'ไม่นับหน่วยกิตให้สำหรับผู้ที่สอบได้ มธ.155 หรือกำลังศึกษาวิชาดังกล่าวอยู่\r\nความรู้ทั่วไปเกี่ยวกับสถิติเชิงพรรณนา เลขดัชนีความน่าจะเป็นทั้งไม่มีเงื่อนไขและมีเงื่อนไข ตัวแปรสุ่มและการแจกแจงความน่าจะเป็นของตัวแปรสุ่ม ค่าคาดหมายมีเงื่อนไขและไม่มีเงื่อนไข การชักตัวอย่างเบื้องต้นและการแจกแจงของตัวสถิติ การประมาณค่าและการทดสอบสมมุติฐานเกี่ยวกับพารามิเตอร์ของประชากรกลุ่มเดียว การอ่านผลลัพธ์จากโปรแกรมสำเร็จรูปทางสถิต'),
('', 'ST326', 'ส.326', 'Applied Probability', 'ความน่าจะเป็นประยุกต์', 3, '(3-0-6)', '', '( ค.111 หรือ ค.211 หรือ ค.216 หรือ คป.101 ) และ ( ส.211 หรือ ส.216 หรือ มธ.155 )', '( MA111 or MA211 or MA216 or AM101 ) and ( ST211 or ST216 or TU155 )', 'Sample space, events, probability measure; conditional probability and independence, odd; random variables and their probability distribution; expected value; cumulative and survival distributions; jointly distributed random variables; conditional distributions; conditional expectation; application of probability in risk management and insurance.\r\n', 'ปริภูมิตัวอย่าง เหตุการณ์ และเมเชอร์ความน่าจะเป็นความน่าจะเป็นมีเงื่อนไขและความเป็นอิสระ ออดส์ ตัวแปรสุ่มและการแจกแจงความน่าจะเป็น ค่าคาดหมาย ฟังก์ชันการแจกแจงสะสมและฟังก์ชันการแจกแจงรอดชีพ ตัวแปรสุ่มแจกแจงร่วมกัน การแจกแจงมีเงื่อนไข ค่าคาดหมายมีเงื่อนไข การประยุกต์ความน่าจะเป็นในการจัดการความเสี่ยงและการประกันภัย'),
('', 'TU050', 'มธ.050', 'English Skill Development', 'การพัฒนาทักษะภาษาอังกฤษ', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Practice basic skills for listening, speaking, reading, and writing in English through an integrated method. Students will acquire a basis to continue to study English at a higher level.', 'ฝึกทักษะภาษาอังกฤษในระดับเบื้องต้น ได้แก่ การฟัง การพูด การอ่าน การเขียน เชิงบูรณาการ เพื่อเป็นพื้นฐานในการพัฒนาทักษะภาษาอังกฤษระดับต่อไป'),
('', 'TU100', 'มธ.100', 'Civic Engagement', 'พลเมืองกับการลงมือแก้ปัญหา', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Instillation of social conscience and awareness of one’s role and duties as a good global citizen. This is done through a variety of methods such as lectures, discussion of various case studies and field study outings. Students are required to organise a campaign to raise awareness or bring about change in an area of their interest. ', 'ปลูกฝังจิตสำนึก บทบาท และหน้าที่ความรับผิดชอบของการเป็นสมาชิกที่ดีของสังคมในฐานะพลเมืองโลก ผ่านกระบวนการหลากหลายวิธี เช่น การบรรยาย การอภิปรายกรณีศึกษาต่างๆ ดูงานเป็นต้น โดยนักศึกษาจะต้องจัดทำโครงการรณรงค์ เพื่อให้เกิดการรับรู้ หรือเกิดการเปลี่ยนแปลง ในประเด็นที่สนใจ'),
('', 'TU101', 'มธ.101', 'Thailand, ASEAN, and the World', 'โลก อาเซียน และไทย', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Study of significant phenomena around the world, in the ASEAN region and in Thailand in terms of their political, economic and sociocultural dimensions. This is done through approaches, theories and principles of social science research via discussion and raising examples of situations or people of interest. The purpose of this is to create a perspective of diversity, to understand the complexity of global interrelationships, to build a global mindset and to be able to challenge old paradigms and open up a new, broader worldview.', 'ศึกษาปรากฏการณ์ที่ส าคัญของโลก อาเซียนและไทย ในมิติทางการเมือง เศรษฐกิจ สังคมวัฒนธรรม โดยใช้กรอบแนวคิด ทฤษฎี และระเบียบวิจัยทางสังคมศาสตร์ ผ่านการอภิปรายและยกตัวอย่างสถานการณ์หรือบุคคลที่ได้รับความสนใจ เพื่อให้เกิดมุมมองต่อความหลากหลายและเข้าใจความซับซ้อนที่สัมพันธ์กันทั้งโลก มีจิตส านึกสากล (GLOBAL MINDSET) สามารถท้าทายกรอบความเชื่อเดิมและเปิดโลกทัศน์ใหม่ให้กว้างขวางขึ้น'),
('', 'TU102', 'มธ.102', 'Social Life Skills', 'ทักษะชีวิตทางสังคม', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Holistic health care, addressing the physical ,emotional ,social ,and spiritual needs ,which is considered. Important skills for success in leading a happy life in society. Students learn to develop their ability in physical health care to manage stress, build emotional security, understand themselves and adapt to psychological, emotional and social problems. Students also learn to understand the meaning of aesthetics, experiencing and appreciating the relationship between art and humanity in different fields, namely visual arts, music, performing arts and architecture. ', 'การดุแลสุขภาพตนเองแบบองค์รวม ทั้งทางด้านร่างกาย อารมณ์ สังคม และจิตวิญญาณ ซึ่งเป็นทักษะสำคัญที่จะช่วยให้ประสบความส าเร็จและใช้ชีวิตในสังคมอย่างเป็นสุข ด้วยการพัฒนาความสามารถใน การดูแลสุขภาพทางกายการจัดการความเครียด การสร้างความมั่นคงทางอารมณ์ การเข้าใจตนเองและการปรับตัวเมื่อเผชิญกับปัญหาทางด้านจิตใจ อารมณ์ และสังคม การเข้าใจความหมายของสุนทรียศาสตร์ การได้รับประสบการณ์และความซาบซึ้งในความสัมพันธ์ระหว่างศิลปะกับมนุษย์ ในแขนงต่างๆ ทั้งทัศนศิลป์ ดนตรีศิลปะการแสดง และสถาปัตยกรรม'),
('', 'TU103', 'มธ.103', 'Life and Sustainability', 'ชีวิตกับความยั่งยืน', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'This course provides an introduction to the importance of life-cycle systems perspectives in understanding major challenges and solutions to achieving more sustainable societies in this changing world. Students will learn about the relationship between mankind and the environment in the context of energy and resource use, consumption and development, and environmental constraints. Furthermore, an examination of social conflict and change from the life-cycle perspective will be used to develop an understanding of potential solution pathways for sustainable lifestyle modifications.', 'การดำเนินชีวิตอย่างเท่าทันกับการเปลี่ยนแปลงของโลก เข้าใจความสัมพันธ์ระหว่างพลวัต ของธรรมชาติ มนุษย์ และสรรพสิ่ง ทั้งสิ่งแวดล้อมสรรสร้าง การใช้พลังงาน เศรษฐกิจ สังคมในความขัดแย้งและการแปรเปลี่ยน ตลอดจนองค์ความรู้ทางวิทยาศาสตร์สิ่งแวดล้อม ที่นำไปสู่การปรับเปลี่ยนวิถีชีวิตสู่ความยั่งยืน '),
('', 'TU104', 'มธ.104', 'Critical Thinking, Reading, and Writing', 'การคิด อ่าน และเขียนอย่างมีวิจารณญาณ', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Development of critical thinking through questioning, analytical, synthetic and evaluation skills. Students learn how to read without necessarily accepting all the information presented in the text, but rather consider the content in depth, taking into account the objectives, perspectives, assumptions, bias and supporting evidence, as well as logic or strategies leading to the author’s conclusion. The purpose is to apply these methods to students’ own persuasive writing based on information researched from various sources, using effective presentation techniques.', 'พัฒนาทักษะการคิดอย่างมีวิจารณญาณผ่านการตั้งคำถาม การวิเคราะห์ การสังเคราะห์ และการประเมินค่า พัฒนาทักษะการอ่านเพื่อจับสาระสำคัญ เข้าใจจุดมุ่งหมาย ทัศนคติ สมมติฐาน หลักฐานสนับสนุน การใช้เหตุผลที่นำไปสู่ข้อสรุปของงานเขียน พัฒนาทักษะการเขียนแสดงความคิดเห็นอย่างมีเหตุผลและการเขียนเชิงวิชาการ รู้จักถ่ายทอดความคิด และเชื่อมโยงข้อมูลเข้ากับมุมมองของตนเอง รวมถึงสามารถอ้างอิงหลักฐานและข้อมูลมาใช้ในการสร้างสรรค์งานเขียนได้อย่างมีประสิทธิภาพ'),
('', 'TU105', 'มธ.105', 'Communication Skills in English', 'ทักษะการสื่อสารด้วยภาษาอังกฤษ', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Development of English listening, speaking, reading and writing skills, focusing on the ability to hold a conversation in exchanging opinions, as well as reading comprehension of academic texts from various disciplines related to students’ field of study.', 'พัฒนาทักษะการฟัง พูด อ่าน และเขียนภาษาอังกฤษโดยมุ่งเน้นความสามารถในการสนทนาเพื่อแลกเปลี่ยนความคิดเห็น และการอ่าน เพื่อทำความเข้าใจเนื้อหาวิชาการในศาสตร์ต่างๆ ที่เกี่ยวข้องกับวิชาชีพของนักศึกษา'),
('', 'TU106', 'มธ.106', 'Creativity and Communication', 'ความคิดสร้างสรรค์และการสื่อสาร', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Creative thought processes, with critical thinking as an important part, as well as communication of these thoughts that lead to suitable results in social, cultural and environmental contexts, at personal, implementation and social levels.', 'กระบวนการคิดอย่างสร้างสรรค์โดยมีการคิดเชิงวิพากษ์เป็นองค์ประกอบสำคัญ และการสื่อสารความคิดดังกล่าวให้เกิดผลสัมฤทธิ์อย่างเหมาะสมตามบริบทสังคม วัฒนธรรม สภาพแวดล้อม ทั้งในระดับบุคคล องค์กร และสังคม'),
('', 'TU107', 'มธ.107', 'Digital Skill and Problem Solving', 'ทักษะดิจิทัลกับการแก้ปัญหา', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Basic computational thinking skill for solving problems and developing new social and economic opportunities. Efficient access and search for information. Information reliability evaluation. Filtering and managing information systematically. Ethical digital usage and professional online communication', 'ทักษะการคิดเชิงค านวณเพื่อการแก้ปัญหาและการพัฒนาโอกาสใหม่ด้านสังคมและเศรษฐกิจความสามารถในค้นหาและการเข้าถึงสารสนเทศได้อย่างมีประสิทธิภาพ การประเมินความน่าเชื่อถือของสารสนเทศ การกลั่นกรองและจัดการสารสนเทศอย่างเป็นระบบ การใช้และจรรยาบรรณด้านดิจิทัล การสื่อสารออนไลน์อย่างมืออาชีพ'),
('', 'TU108', 'มธ.108', 'Self-Development and Management', 'การพัฒนาและจัดการตนเอง', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Coping with and adaptation to university life. Development of social skill and emotional intelligence. Self understanding and planning for the future. Personality and social etiquette. Learning to live harmoniously and respectfully with others and the society', 'การจัดการและการปรับเข้ากับชีวิตในรั้วมหาวิทยาลัยท่ามกลางความหลากหลายและเสรีภาพ การพัฒนาทักษะทางสังคมและความฉลาดทางอารมณ์ การเข้าใจตนเองและการวางแผนอนาคต การพัฒนาการเรียนรู้ตลอดชีวิต และการอยู่ร่วมกับผู้อื่นอย่างสงบสุขและเคารพซึ่งกันและกัน'),
('', 'TU109', 'มธ.109', 'Innovation and Entrepreneurial Mindset', 'นวัตกรรมกับกระบวนคิดผู้ประกอบการ', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Risk assessment and creating new opportunities. Thinking and planning as an entrepreneur. Decision making and entrepreneurial venture development. Business communication for delivering concept or initiative in an efficient, effective and compelling manner. Social shared value creation.', 'การประเมินความเสี่ยงและการสร้างโอกาสใหม่ การคิดและการวางแผนแบบผู้ประกอบการ การตัดสินใจและการพัฒนาธุรกิจ การสื่อสารเชิงธุรกิจและการสร้างแรงจูงใจอย่างมีประสิทธิภาพ การสร้างคุณค่าร่วมเพื่อสังคม'),
('', 'TU122', 'มธ.122', 'Law in Everyday Life', 'กฎหมายในชีวิตประจำวัน', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'To study general aspects of law as correct patterns of human conduct in society. To equip learners with basic principles of public law (rules of law), and its values which are associated with citizens’ moral core. To provide basic knowledge in public law and private law, involving the issues of rights and duties, dispute settlement, Thai Justice procedures, the usage and interpretation of law principles, with an emphasis on case studies in our daily lives.', 'ลักษณะทั่วไปของกฎหมาย ในฐานะที่เป็นแบบแผนความประพฤติของมนุษย์ในสังคม หลักการพื้นฐานของนิติรัฐ (rule of law) คุณค่าของกฎหมายในฐานะที่เชื่อมโยงกับหลักคุณธรรมของประชาชน ความรู้พื้นฐานในเรื่องกฎหมายเอกชนและกฎหมายมหาชนที่พลเมืองในระบอบประชาธิปไตยควรต้องรู้ทั้งในด้านของสิทธิ และในด้านของหน้าที่ การระงับข้อพิพาทและกระบวนการยุติธรรมของไทย หลักการใช้สิทธิ หลักการใช้และการตีความกฎหมาย โดยเน้นการศึกษาจากกรณีตัวอย่างที่เกิดขึ้นจริงในชีวิตประจำวัน'),
('', 'TU142', 'มธ.142', 'Man and Biological Science', 'มนุษย์กับวิทยาศาสตร์ชีวภาพ', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'To study the nature and origin of life, the evolution of life, genetics, reproduction and stages of human aging. Applying knowledge of life sciences for the benefit of agriculture, industry, medicine and the environment as well as the study of the impact of biotechnology on human life.', 'ธรรมชาติและก าเนิดชีวิต วิวัฒนาการของสิ่งมีชีวิต พันธุกรรม การสืบพันธุ์ พัฒนาการและความชราของ มนุษย์ การน าความรู้ทางวิทยาศาสตร์ชีวภาพมาใช้ประโยชน์ทางด้านการเกษตร การอุตสาหกรรม การแพทย์และสิ่งแวดล้อม รวมทั้งศึกษาผลกระทบทางเทคโนโลยีชีวภาพที่มีต่อคุณภาพชีวิตมนุษย์ '),
('', 'TU143', 'มธ.143', 'Man and Environment', 'มนุษย์กับสิ่งแวดล้อม', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', 'Fundamentals of natural and man-made ecosystem, biogeochemical cycles, interaction between human society and global environment. Topics include the impacts of science and technology on human population, natural ecosystems, biodiversity, pollution, climate change, solid and hazardous waste and disaster.', 'พื้นฐานด้านระบบนิเวศธรรมชาติและมนุษย์สร้างขึ้น วัฏจักรชีวธรณีเคมี ปฏิสัมพันธ์ระหว่างสังคมมนุษย์ และสิ่งแวดล้อมของโลก รวมถึงผลกระทบของวิทยาศาสตร์และเทคโนโลยีที่มีต่อประชากรมนุษย์ระบบนิเวศ ธรรมชาติ ความหลากหลายทางชีวภาพ มลพิษ การเปลี่ยนแปลงสภาพภูมิอากาศ ขยะมูลฝอยของเสียอันตราย และภัยพิบัติ'),
('', 'TU152', 'มธ.152', 'Fundamental Mathematics', 'หลักพื้นฐานทางคณิตศาสตร์', 3, '(3-0-6)', '', 'ไม่มี คุณสามารถลงทะเบียนวิชานี้ได้เลยครับ', 'None, you can register for this course.', '(This course is for students who have already studied mathematics in high school and have gained not less than 16 credits or as demanded by their faculty.)\r\nTo prove logical rules, methods of proofs, arguments, mathematical induction, proofs of theorems of inequalities and absolute values, inequalities solving, functions, type of functions, applications of functions, curve sketching, partial fractions decomposition, solving of simple systems of linear equations. ', '(วิชานี้สำหรับนักศึกษาที่เคยเรียนคณิตศาสตร์ในระดับมัธยมศึกษาตอนปลายไม่ต่ำกว่า 16 หน่วยกิตหรือเป็น วิชาที่คณะ/สาขาวิชาบังคับให้เรียน)\r\nหลักเกณฑ์ทางตรรกศาสตร์ที่ใช้ในการพิสูจน์ วิธีการพิสูจน์แบบต่าง ๆ การอ้างเหตุผล การอุปนัยเชิง คณิตศาสตร์ การพิสูจน์ในทฤษฎีเกี่ยวกับอสมการและค่าสัมบูรณ์ การแก้อสมการ ฟังก์ชัน ฟังก์ชันชนิดต่างๆ โจทย์ ประยุกต์ของฟังก์ชัน การเขียนกราฟของฟังก์ชัน การแยกเศษส่วนออกเป็นเศษส่วนย่อย การแก้ระบบสมการเชิงเส้น อย่างง่าย');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cgroup`
--
ALTER TABLE `cgroup`
  ADD PRIMARY KEY (`groupCode`);

--
-- Indexes for table `courses-61`
--
ALTER TABLE `courses-61`
  ADD PRIMARY KEY (`courseID_EN`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
